.gitignore
README.md
tox.ini

Remove Python 3.6 from tox and readme. Fixes #16.

Deprecate python 3.6

---

nmdc_server/query.py
tests/test_query.py

The faceting query should always return counts of fields in the current table.  There were cases when a faceting operation was throwing an error due to invalid join condition in the main query.  The correct behavior is to return an empty dictionary.  For example, faceting on the 'study` table over the attribute `biosample_id` returns no results because no studies contain that field.

Prevent errors when faceting over an attribute in a foreign table

---

nmdc_server/aggregations.py
nmdc_server/api.py
nmdc_server/crud.py
nmdc_server/schemas.py
setup.cfg

@subdavis This updates the summary response to include the attribute type.  I replaced the per attribute count because I'm not sure it's that useful, but I can make it a nested object type if needed.

Return attribute types in database summary

---

nmdc_server/models.py
nmdc_server/schemas.py

There is a problem coercing sqlalchemy association proxies to lists.
Because this is a blocker, I'm commenting these fields out until I come
up with a solution.

Fix query error due to incorrect schema

---

nmdc_server/aggregations.py
nmdc_server/api.py
nmdc_server/crud.py
nmdc_server/schemas.py
tests/test_app.py

Adding this new endpoint so that the aggregations can be optimized at some point in the future.
```
GET /api/stats
=> {
"data_size": 9971939611997,
"habitats": 21,
"lipodomics": 0,
"locations": 23,
"metabolomics": 0,
"metagenomes": 834,
"metatranscriptomes": 130,
"organic_matter_characterization": 0,
"proteomics": 0,
"studies": 13
}
```

Add a new endpoint that accumulates stats to be shown on the main page

---

nmdc_server/errors.py
nmdc_server/query.py
tests/test_query.py

This would be better placed on the schema, but with dynamic attributes
in "annotations" it can't really be done.
Fixes #63

Catch query errors when provided invalid attributes

---

web/src/views/Search/Search.vue

When you click a vis option to add condition, it shuldn't get duplicated ifyou click again.

Prevent double-adding conditions from clicking vis

---

nmdc_server/schemas.py

Fixes a 500 error that was sometimes occurring.

Handle missing envo terms in biosample response

---

nmdc_server/aggregations.py
nmdc_server/query.py
tests/test_query.py

Done to enable querying by principal investigator name.  Like with the envo fields, the code to do it is a bit ugly because you can't group_by and association proxy field.  This is making clear that there needs to be better hooks for per-attribute query customization in a future refactor.
Fixes #74

Add the ability to query association proxy fields

---

.docker-env
docker-compose.yml

Not sure what the intention was here, but right now the docker-compose stack won't start because the password is missing.  Docker-compose won't interpolate strings defined elsewhere in the .env, you can check with `docker inspect`:
```
"PGUSER=postgres",
"PGDATA=/var/lib/postgresql/data/pgdata",
"PGDATABASE=nmdc",
"PGHOST=db",
"POSTGRES_URI=\"postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}/${PGDATABASE}\"",
"POSTGRES_PASSWORD=postgres",
"PGPASSWORD=\"${POSTGRES_PASSWORD}\"",
"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/postgresql/12/bin",
"GOSU_VERSION=1.12",
"LANG=en_US.utf8",
"PG_MAJOR=12",
"PG_VERSION=12.3-1.pgdg100+1"
```

Fix docker env vars

---

create_database.py
nmdc_server/query.py

Also removes principal investigator from the project because it exists
on the study.

Guard against invalid association proxy queries on unrelated tables

---

docker-compose.yml
web/Dockerfile
web/nginx.conf.template
web/start.sh

Taken from https://serverfault.com/a/593003 with some additional logic to avoid hard coding the DNS server which could change on spi.  That line might break in some cases (especially if using `--network host`), but this is the only solution I could come up with that doesn't involve commercially licensed nginx modules.  For the moment, it appears to be working both through docker-compose and the production deployment.

Force nginx to update dns on spin

---

nmdc_server/api.py
nmdc_server/app.py
nmdc_server/auth.py
nmdc_server/config.py
nmdc_server/fakes.py
setup.py
tests/conftest.py
tests/test_auth.py

This is mostly a placeholder as we aren't yet storing user information into the database.  It relies on a signed session cookie to ensure authentication is valid.  No attempt is made at refreshing expired oauth tokens.
The only endpoints affected by this change are the unused resource creation endpoints.

Add authentication related endpoints using ORCID as a provider

---

web/src/views/IndividualResults/AttributeList.vue

I removed the ability to omit the table name from the search conditions a while back.  This cleans up a place where table name was not being added.

Add table name to all conditions

---

nmdc_server/api.py
nmdc_server/binning.py
nmdc_server/crud.py
nmdc_server/errors.py
nmdc_server/query.py
setup.py
tests/test_binning.py

For each of the models, this adds a new endpoint for faceting that looks like this:
```
POST /biosample/binned_facet attribute=depth num_bins=5
{
"bins": [
0, 
400,
800,
1200,
1600,
2000
],
"facets": [204, 0, 187, 0, 1]
}
```
This means, 204 results are contained in the range [0, 400), 187 in [800, 1200), and 1 in [1600, 2000].
You can provide a custom range:
```
POST /biosample/binned_facet attribute=depth num_bins=5 minimum=20 maximum=100
{
"bins": [
20.0,
36.0,
52.0,
68.0,
84.0,
100.0
],
"facets": [31, 0, 0, 0, 0]
}
```
This works for date types as well:
```
/biosample/binned_facet attribute=collection_date num_bins=5
{
"bins": [
"2011-06-15T00:00:00",
"2012-10-12T09:36:00",
"2014-02-09T19:12:00",
"2015-06-10T04:48:00",
"2016-10-07T14:24:00",
"2018-02-05T00:00:00"
],
"facets": [21, …
```

Add server side binning for numeric and date attributes

---

nmdc_server/models.py
nmdc_server/query.py
nmdc_server/schemas.py
setup.py

This is fairly simple to accomplish via [query time expressions](https://docs.sqlalchemy.org/en/14/orm/mapped_sql_expr.html#query-time-sql-expressions-as-mapped-attributes), but it is something of a brute force solution because it repeats subqueries twice.  This may be a performance issue when I get to implementing workflow execution summaries.  The solution will be to implement these subqueries as lateral joins, but that will take a more significant refactor.
One caveat of the current implementation is that `sample_count` will be `null` when fetching from `/study/{id}`.  I don't think this is a problem for the current use case.  I would likely use a stored, denormalized value in this case if the need arises.

Implement sample_count summary in study search results

---

nmdc_server/models.py
nmdc_server/query.py
nmdc_server/schemas.py

This implements the omics processing summary needed for #191.  As I suspected, doing the aggregation this way is noticeably slower due to the repeated subqueries.  A lateral join will likely remove most of the performance penalty.  I'll work on it after we get a proof of concept working.

Add omics_counts summary to study schema

---

nmdc_server/models.py
nmdc_server/schemas.py

This implements the `omics_data` attribute of #191.  The only difference is that there is an extra object (the workflow execution object) between the sample and data_object.  For example:
```json
[
{
"id": "nmdc:23ed2430a9b1e9d120c4c97a2a7b8a5b",
"name": "ReadQC activiity 1778_72754",
"type": "nmdc:ReadQCAnalysisActivity",
"git_url": "https://github.com/microbiomedata/ReadsQC/releases/tag/1.0.0",
"started_at_time": "2020-03-20T00:00:00",
"ended_at_time": "2020-03-20T00:00:00",
"execution_resource": "NERSC - Cori",
"project_id": "gold:Gp0108335",
"outputs": [
{
"id": "nmdc:bf13805c9b0af6fec35734378f5f5fb0",
"name": "filterStats.txt",
"description": "Filtered read data stats for gold:Gp0108335",
"file_size_bytes": 288,
"md5_checksum": null
},
{
"id": "nmdc:88b3d02641c1974a7e6d3f677172939e", …
```

Add omics_data information to biosample search results

---

nmdc_server/alembic.ini
nmdc_server/api.py
nmdc_server/crud.py
nmdc_server/migrations/versions/68a0445e19bf_add_file_downloads.py
nmdc_server/models.py
nmdc_server/schemas.py
web/nginx.conf.template

This endpoint requires login and stores the following information from the request:
* orcid
* data object id
* user agent string
* ip address
* current time stamp
None of this information is exposed publicly.  It should allow us to derive any summary statistics we want by aggregations on this table.

Add a redirection service for data objects

---

nmdc_server/cli.py
nmdc_server/fakes.py
nmdc_server/ingest/all.py
nmdc_server/ingest/pipeline.py
nmdc_server/migrations/versions/18e52534911c_remove_gene_function_count.py
nmdc_server/models.py
nmdc_server/schemas.py

This add the gene function relations for metagenome annotations.  As I suspected, this makes running ETL on deploy (and testing it in github actions) unsustainable as it will take at least 15 minutes (probably more).  I'm going to have look into a new strategy for manually triggering the ETL.

Add gene functions from metagenome annotations

---

README.md
nmdc_server/api.py
nmdc_server/cli.py
nmdc_server/fakes.py
nmdc_server/ingest/all.py
nmdc_server/ingest/biosample.py
nmdc_server/ingest/project.py
nmdc_server/migrations/versions/a9bf0258c0d2_invert_relationship.py
nmdc_server/migrations/versions/e2df18f14429_nullable_study.py
nmdc_server/models.py
nmdc_server/query.py
nmdc_server/schemas.py
prestart.sh
tests/test_query.py
tox.ini

This was a mistake in the data model that needs to be corrected now that there are multiple projects per biosample.
A couple of weird things about the new schema:
* biosample_id is nullable on the project because we don't have biosample information on all projects
* study_id exists on both biosample and project so that queries can be joined both ways.  This will be unnecessary if we make biosample_id on project non-nullable.
I'm only 80% sure the way the tables are being joined now produces the expected result.  It's tricky with two different ways to join with the study table.  We will want to have the people who know the data better vet the search results once we have the data import ironed out.
@subdavis I don't think this will break anything you are working on.  The only big difference …

Invert the relationship between biosample and project

---

nmdc_server/crud.py
nmdc_server/ingest/data_object.py
nmdc_server/models.py
nmdc_server/query.py
nmdc_server/schemas.py
tests/test_query.py

This is fairly simple because gene functions aren't queryable on their own.  It adds support to all of the search and faceting endpoints the following condition:
```
{
"table": "gene_function",
"field": "id",
"value": "KEGG.ORTHOLOGY:K06207"
}
```
Note the value has to contain the `KEGG.ORTHOLOGY:` prefix.  The client should add that, I could have the server add the prefix, but my understanding is we may add id's from different databases.  This could help disambiguate them.

Add gene function to query conditions

---

nmdc_server/query.py

This speeds up searches by eliminating the need to do a full table scan on gene_function and related tables.  Searches on actual gene_functions use a foreign key constraint and so are much faster.

Only join gene function table if necessary

---

web/src/components/Presentation/UpSet.vue
web/src/views/Search/Search.vue

Adding a draft of the UpSet plot to the search results view. It currently uses dummy data.

Add example UpSet plot

---

nmdc_server/ingest/project.py
nmdc_server/schemas.py

Adds server side support for #230 
The raw data is returned with the project object as the property "outputs", e.g.
```json
{
"id": "gold:Gp0115663",
"name": "Groundwater microbial communities from the Columbia River, Washington, USA, for microbe roles in carbon and contaminant biogeochemistry - GW-RW metaG T2_23-Sept-14",
"description": "Coupling Microbial Communities to Carbon and Contaminant Biogeochemistry in the Groundwater-Surface Water Interaction Zone",
...,
"outputs": [
{
"id": "jgi:55d740280d8785342fcf7e39",
"name": "9422.8.132674.GTTTCG.fastq.gz",
"description": "Raw sequencer read data",
"file_size_bytes": 2861414297,
"md5_checksum": null,
"url": null
}
]
}
```

Return raw data associated with an omics_processing

---

.docker-env
.env.example
Dockerfile.worker
docker-compose.yml
nmdc_server/api.py
nmdc_server/auth.py
nmdc_server/celery.py
nmdc_server/config.py
nmdc_server/jobs.py
prestart.sh
setup.py
tests/conftest.py
tests/test_auth.py
tox.ini

This removes data ingest from the server start.  I added a task to ping the worker that I will use to get the production stack working.  Once that is done, I will migrate the ingestion code into a celery task that can be manually triggered via an endpoint.
I have also added the concept of an admin user that is allowed to make data changes.  Because we don't have a user table, it is just a hard coded set of orcids (currently only me).  We can add additional admins via PR's until we find the need to generate a user table.

Add a celery worker for performing async tasks

---

nmdc_server/query.py

I don't think outer joins between many of these tables is necessary (at least given the current schema).  This speeds everything up quite a bit, so I'm going to try deploying this without the pre-baked study response to see what it's like.
There are a few other places where I think I can get away with similar optimizations, so I might not need a full refactor to get performance good enough for the current data size.

Use inner joins for study and biosample queries

---

nmdc_server/fakes.py
nmdc_server/ingest/doi.py
nmdc_server/ingest/study.py
nmdc_server/migrations/versions/f1cd153d1a16_add_doi_table.py
nmdc_server/models.py
nmdc_server/schemas.py
setup.py

Adds to the study response a `publication_doi_info` object that contains the doi information returned by doi.org for each doi referenced by the study.
Alternatively, I could have created an endpoint that acts just like doi.org.  What I implemented minimizes the number of requests and queries made at the expense of a larger response size for the study endpoints.
Implements the server side of #286 
Fixes #136

Add doi info collected from doi.org

---

nmdc_server/models.py
nmdc_server/query.py
nmdc_server/schemas.py

Adds `omics_processing_counts` to the study search response which contains aggregated counts of the omics processings (projects) grouped by type.
Implements the server part of #298

Add omics_processing counts to study search response

---

.docker-env
docker-compose.yml
nmdc_server/cli.py
nmdc_server/config.py
nmdc_server/database.py
nmdc_server/ingest/all.py
nmdc_server/jobs.py
nmdc_server/migrations/env.py
prestart.sh
tox.ini

This still needs some work on the spin infrastructure to perform replacement from the ingest to the production database.  I'm going to attempt it manually a couple of times before doing that.

Ingest data into a dedicated database to limit downtime

---

nmdc_server/aggregations.py
nmdc_server/attribute_units.py
nmdc_server/schemas.py
setup.py

This adds a new optional property in the database summary for an attribute that contains normalized unit information.  The unit information is currently only available for `biosample.depth`, where the response looks like this:
```json
"depth": {
"count": 49,
"min": 0,
"max": 2000,
"type": "float",
"units": {
"name": "meter",
"abbreviation": "m",
"dimensionality": [
{
"quantity": "[length]",
"exponent": 1
}
]
}
}
```
This is primarily to define a unit aware interface for the client to use.  We still need to define how to extract this information from the schema.
Ping @subdavis for using this information in the web client somehow.
Addresses #338

Include unit information with summary endpoint

---

web/src/colors.js
web/src/components/Presentation/ConditionChips.vue
web/src/v2/components/DataObjectTable.vue
web/src/v2/components/FacetedSearch.vue
web/src/v2/components/MenuContent.vue
web/src/v2/components/TooltipCard.vue
web/src/v2/views/IndividualResults/IndividualTitle.vue
web/src/v2/views/Search/BiosampleVisGroup.vue
web/src/v2/views/Search/Layout.vue
web/src/v2/views/Search/Sidebar.vue

I think this takes care of all the feedback we decided to move on from https://www.figma.com/file/h3v0xOrdZSYWSCRZhxQcXw/Improvements-based-on-'Mockup-Report-SGCI-NMDC-Usability-Consulting.pdf'?node-id=0%3A1
* Still using lorem ipsum for hover text.  I can switch these to full dialogs with a dismiss button if you think they need more than just a sentence or two.
* I went with sort of a hybrid for the download table change.  I liked the dedicated workflow header more than just the darkened background.  I also added a duplicate workflow header on the top of the N > 1th page of results so you don't have to remember what workflow section you're in page-to-page.
* I didn't make it collapsible because there's already a lot going on in here and it seemed premature.  Also, only some omics types …

Incorporate UX Design Feedback Round 2

---

nmdc_server/database.py
nmdc_server/ingest/all.py
nmdc_server/migrations/versions/04137e962f0f_add_multiomics.py
nmdc_server/models.py
nmdc_server/multiomics.py
nmdc_server/query.py
nmdc_server/schemas.py
tests/test_query.py

This adds a new denormalized column called `multiomics` to the biosample table.  This is an integer representing a bit mask of omics processing types available for the sample.  Bit values are encoded in an enum:
```python
class MultiomicsValue(Enum):
mb = 0b10000
mg = 0b01000
mp = 0b00100
mt = 0b00010
om = 0b00001
```
A new schema for querying this information is also implemented:
```python
{
"table": "biosample",
"field": "multiomics",
"op": "has",
"value": 6
}
```
This will query for biosamples that have **both** metatranscriptome and metaproteomic omics_processing.  (They might have others as well.)
Implements the server side of #367.

Add the ability to query by the existence of multiple omics types

---

nmdc_server/aggregations.py
nmdc_server/api.py
nmdc_server/bulk_download_schema.py
nmdc_server/crud.py
nmdc_server/data_object_filters.py
nmdc_server/database.py
nmdc_server/fakes.py
nmdc_server/filters.py
nmdc_server/ingest/all.py
nmdc_server/ingest/data_object.py
nmdc_server/ingest/omics_processing.py
nmdc_server/ingest/pipeline.py
nmdc_server/migrations/versions/7f9314e44f22_bulk_download.py
nmdc_server/migrations/versions/c4d63f4206fb_add_file_type.py
nmdc_server/migrations/versions/da4a0d10abcf_add_workflow_type.py
nmdc_server/models.py
nmdc_server/pagination.py
nmdc_server/query.py
nmdc_server/schemas.py
nmdc_server/table.py
tests/test_download.py
web/nginx.conf.template

fixes #354
I still want to do a little more refinement of this before merging.  Hopefully, @subdavis can look it over before then and see if it matches his expectations of the UI.  
Biosample search
================
This changes the biosample search endpoint to include a new data_object_filter attribute, e.g.:
```json
{
"conditions": [],
"data_object_filter": [{"workflow": "nmdc:ReadQCAnalysisActivity", "file_type": "fastqc"}]
}
```
Each filter object contains an optional workflow enum and file type (currently ignored until we get data for it).  A workflow is one of the following:
```
nmdc:ReadQCAnalysisActivity
nmdc:MetagenomeAssembly
nmdc:MetagenomeAnnotation
nmdc:MetaProteomicAnalysis
nmdc:MAGsAnalysisActivity
nmdc:ReadbasedAnalysis
nmdc:NomAnalysisActivity …
```

Bulk download API

---

web/src/data/api.ts
web/src/v2/components/DataObjectTable.vue

I've noticed that some still don't have a `file_type` and `file_type_description`.  To prevent these from being blank, I fallback on `name` and `description`.
However, for these types, it is impossible to include these files in bulk download.  For example, these files in MAGs Analysis:
You can download `metagenome bins` and `checkm statistics` but the `bins.*` files have no `file_type` and `file_type_description` and cannot be selected.

Switch description and type

---

docker-compose.dev.yml
docker-compose.yml

This allows the use of alembic command line from the host, and the postgres shell.

Expose postgres to host in development configuration

---

nmdc_server/query.py

The latest FastAPI release (0.68) made tuple return types an explicit error.
See https://github.com/tiangolo/fastapi/issues/466

Fix CI that broke with FastAPI release

---

nmdc_server/ingest/envo.py
tests/test_envo.py

Remove all parts of the tree that are unreachable based on the set of terms present in the biosample table.
This is an improvement but not the final goal. In the current dataset, there are biosamples whose envo values do not fall under the three roots we've manually identified. So, this tree does not span the entire biosample set, but it does span most of it.
A more robust solution will involve more analysis of the dataset to comprehensively identify all roots and return an array of root nodes for each of the three facets.

Prune Envo tree

---

Dockerfile.worker

Fixes bug introduced in #478 `celery.py -> celery_config.py` rename broke container build.

Change celery reference

---

README.md
nmdc_server/cli.py
nmdc_server/config.py
nmdc_server/database.py
setup.py

Here's my cheap attempt at a poor man's version of Django's `shell_plus` in this stack. It gives us some free imports, and a SQL debugging option. Next step would be to add a way to pass it a script, or to make all the ipython options generally more configurable via pass-through.

Basic ipython shell helper

---

nmdc_server/ingest/envo.py

I believe this is now equivalent functionality to the algorithm @jeffbaumes laid out. The only thing it doesn't do is delete root nodes, which could be done as a separate step if we want the ability to remove one extra node. (I had originally tried to do it all at once, but the function became complicated and difficult to reason about.)
I would love for someone to come up with a proof about the need to detect changes and run multiple passes. I tried reasoning it out but my brain broke and I gave up so I could get this merged since it gets us 99% to the goal.

Prune internal envo tree nodes statically

---

web/src/components/Presentation/UpSet.vue
web/src/data/api.ts
web/src/data/protobuf-descriptor.json
web/src/encoding.ts
web/src/views/Search/BiosampleVisGroup.vue

fixes #390
This doesn't exactly address that issue because the backend doesn't support `AND` operations for terms for the same field/table.  The convention is `AND` across facets, `OR` within facets.  In order for clicking one of these bars to behave expectedly, we would need `AND` across and within the `omics_processing.omics_type` facet.
UPDATE: see #390 for explanation of how to resolve this with multiomics.

Upset click

---

.github/workflows/deploy.yml
.github/workflows/server.yml
.gitmodules
README.md
web/package.json
web/src/components/MenuContent.vue
web/src/data/api.ts
web/src/encoding.ts
web/src/main.ts
web/yarn.lock

I found this approach simpler than a backend ingest.
* Install https://github.com/microbiomedata/nmdc-schema as a git submodule
* use `postinstall` to install this submodule on `yarn install`
* Bundle the schema JSON file using webpack
This comes with the added benefit that typescript can enforce the mappings declared in `encoding.ts` because of `resolveJsonModule`.
See how, in the screenshot below, you can get a nice literal type by introspecting the values in the json object.  So if a name changes in a future version of the NMDC schema, it will actually break the build.
This is probably less code than going the ingest route
fixes #505

Include definitions from schema

---

nmdc_server/crud.py
nmdc_server/query.py
nmdc_server/table.py
web/src/components/MenuContent.vue
web/src/encoding.ts

@zachmullen I really quite disliked the client-side transformation of KEGG terms, so I did it on the server side.
This implementation isn't perfect, and it should probably be some kind of join, but it's relatively well isolated in the `transformCondition` function IMO.
It also makes the search functions case-insensitive.
This is a basic version where you can paste in the new terms and they'll be transformed on the server.

Kegg search

---

docker-compose.yml

The postgres logs during MGA ingest were emitting these warnings:
```
2021-09-27 19:06:20.211 UTC [26] LOG:  checkpoints are occurring too frequently (26 seconds apart)
2021-09-27 19:06:20.211 UTC [26] HINT:  Consider increasing the configuration parameter "max_wal_size".
```
This is just some light tuning, it may or may not have a substantial impact on ingest performance.

Bump max WAL size from 1GB (default) to 2GB

---

nmdc_server/config.py
nmdc_server/database.py
setup.py

I've already decreased the worker count on prod. My hypothesis is that that (along with this change) will fix the connection limit errors we've seen in Sentry. I will resolve them once I merge.

More database tuning

---

setup.py

No idea what happened.  Seems like an exported symbol disappeared 
https://github.com/encode/httpx/blob/master/CHANGELOG.md
```ImportError: cannot import name 'USE_CLIENT_DEFAULT' from 'httpx' (/usr/local/lib/python3.8/site-packages/httpx/__init__.py)```

Fix httpx dependency issue

---

Dockerfile
Dockerfile.worker
setup.py

Alpine and python don't mix well [1] [2]
[1] https://github.com/tiangolo/uvicorn-gunicorn-docker#-alpine-python-warning
[2] https://www.notion.so/A-Comprehensive-Guide-for-Switching-to-Poetry-b452ad4d816a4cdda3726847c74fc21f#f3405cef8fc043508dfcdd2115b14cd4
Because there are no wheels for alpine, builds are taking forever.  Switch to debian base images.  Drop all the manual installation of build requirements and just use wheels.

Switch from Alpine to debian

---

nmdc_server/crud.py
nmdc_server/data_object_filters.py

Bug excluded emsl from bulk download.  Null check was redundant, passed responsibility on to get_local_data_url which will either generate a valid path or return None.
Tested working locally.

Bugfix support bulk emsl

---

docker-compose.yml
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/Components/SubmissionStepper.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts

* Switch to sheets_and_friends for github pages hosting
* Drop submission page
* Allow download of invalid spreadsheet
* Add submit button to the bottom of the DH page.
The following items are blockers for getting this fix deployed
fixes https://github.com/microbiomedata/DataHarmonizer/issues/139
fixes #601 
fixes #550
fixes #591

Submission portal changes for GSP

---

web/src/views/SubmissionPortal/HarmonizerView.vue

Re-run export routine instead of using last known copy from validation.
Note that this sorta eliminates the relationship between validation and download.  You can enter valid data, validate it, break it again, not validate it again, and download it.
fixes #609

Re-export before download

---

nmdc_server/ingest/kegg.py

```
"name":"K00626  ACAT, atoB; acetyl-CoA C-acetyltransferase [EC:2.3.1.9]"
```
```
"name":"K00626"
```

Allow missing kegg description text

---

web/package.json
web/yarn.lock

Required by webpack dev server in HTTPS mode, which we don't use.
This pin may break that feature, but it doesn't matter.

Node forge 1.3.0

---

nmdc_server/api.py
nmdc_server/auth.py
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/Components/TemplateChooser.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts
web/src/views/SubmissionPortal/store/index.ts

* Fixes backend admin checking logic.
* Update submission portal template choice logic.
* If JGI/EMSL, only enable soil.
* if user has uploaded metadata, disable template form and prompt to clear form.
* if they have any non-doe enabled, allow all base packages
* Templates aren't configured properly: air and misc should be enabled.
* Adds 4 new administrators.

Updates for submission portal:

---

web/src/App.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts

* Make sidebar collapsible, move to the right side.
* Move error dialog into toolbar.
* Reorder controls to make it clear what is required and what are tools.

Reorganize submission portal

---

web/src/views/SubmissionPortal/harmonizerApi.ts

Fix a template matching bug that causes `emsl_jgi_mg` to match before `jgi_mg` if only JGI metagenome sample types are selected.

Fix matching order

---

web/Dockerfile

The mainline image broke compatibility with a third party module (modzip).  Drop back to stable to fix build.
https://www.nginx.com/blog/nginx-1-6-1-7-released/

Fix nginx build

---

nmdc_server/jobs.py

`SubmissionMetadata` has a foreign key to `User` that is violated when
ingested out-of-order.

Reorder merge of `SubmissionMetadata` to after `User`

---

web/src/components/Presentation/AttributeItem.vue
web/src/components/Presentation/AttributeList.vue

Closes part of #740 
This adds the geographic location name to the sample detail page.

Show geographic location (city/state) in sample detail page

---

web/src/components/Presentation/AttributeItem.vue
web/src/components/Presentation/AttributeList.vue

Closes part of https://github.com/microbiomedata/nmdc-server/issues/740
This remove the "Env ___ Id" attributes in favor of more descriptive attributes in the sample detail page.

Show friendly environmental terms in sample detail page

---

web/src/views/SubmissionPortal/HarmonizerView.vue

Closes #752 
We previously used JavaScript to intercept the scrolling behavior and block over-scrolling (to prevent accidental back-button triggering). This is the more portable solution, but becomes difficult when the `div`'s size is dynamic. In those cases, the JavaScript blocking may "lock up" due to incorrect window size calculations.
This PR replaces the JavaScript with CSS to accomplish the same. It is ignored in [Safari (until new version 16)](https://caniuse.com/?search=overscroll-behavior), but is more performant and robust to dynamic `div`s.

Use CSS to prevent back-button on scroll

---

nmdc_server/cli.py
nmdc_server/jobs.py
prestart.sh

Resolves part of #765:
- Put ingest and migration in Postgres transactions. This will ensure consistency of the data, so the final state of the data is guaranteed.
- Move migration step from separate process to part of the entrypoint script, which first runs backup, then migration, then start server

Migration fixes

---

nmdc_server/migrations/versions/ffaec255fe68_swap_columns.py
web/yarn.lock

Closes https://github.com/microbiomedata/sheets_and_friends/issues/144
The `sheets_and_friends` version is now based on https://github.com/microbiomedata/sheets_and_friends/commit/5173ebd84b5ef2ab855d9497d7b7e1edee50090d.
This required a database data migration, so backups have been made.

Swap columns

---

nmdc_server/app.py

App startup failed with:
```
RuntimeError: The Sentry Python SDK can now automatically support ASGI frameworks like Starlette and FastAPI. Please remove 'SentryAsgiMiddleware' from your project. See https://docs.sentry.io/platforms/python/guides/asgi/ for more information.
```
This PR removes `SentryAsgiMiddleware` from our project as the error suggests.

Remove `SentryAsgiMiddleware`

---

web/src/components/ClusterMap.vue

Resolves #783 
Previously, when filtering through data using the sidebar would cause the map bounds to change, the map would zoom in too far if the results of the query were small. Now, when the map bounds change due to updated search queries, there is a maximum zoom level. This allows users to maintain context for where the data is without needing to zoom back out. Users can still zoom in towards the data.
Without max zoom:
With max zoom = 5:

Prevent zooming too far when map data changes

---

setup.py
web/src/components/Presentation/DateHistogram.vue
web/src/components/Presentation/TimeHistogram.vue
web/src/views/Search/BiosampleVisGroup.vue

Fixes #675
Instead of using a slider to interact with the date histogram on the home page of the data portal, users can now click and drag to select an area. The selection can be moved, stretched, and shrank by interacting with the highlighted area. The area is responsive to a change in the query (i.e. selecting a date range from the sidebar).

Add brush to time histogram

---

nmdc_server/ingest/study.py
nmdc_server/jobs.py
nmdc_server/migrations/versions/86f42a05252b_ck_doi_format.py
nmdc_server/models.py
nmdc_server/schemas.py
web/src/data/api.ts
web/src/views/IndividualResults/StudyPage.vue

Closes #772
A study's DOI information is related to:
- the study's produced dataset
- publications using the dataset
Historically, the type of each of the study's DOIs was indicated via attributes on the DOI information. The schema has since changed  so that each study can indicate separately its dataset's DOI and publication DOIs. The backend supports this schema, but the frontend was not updated to.
This PR:
- updates the frontend to use the explicit DOI form
- normalizes the form of DOI data (previously could be a URL or just the DOI)
- conditionally renders the dataset's DOI to hide this information if not available

Fix DOI representation

---

nmdc_server/alembic.ini
nmdc_server/migrations/versions/3be1e63ce89b_.py

#797 and #798 contained alembic migration files that resulted in a state of multiple `head` revisions, which broke running `nmdc_server`.
This PR addresses this by merging the revisions via `alembic merge heads`

Merge conflicting migrations

---

.github/workflows/server.yml
Dockerfile
Dockerfile.worker
setup.py
tox.ini

This change updates the minimum python version required for `nmdc-server` to 3.9.
With #797, our migration script and database supports ingest of data compliant with NMDC schema version 7. This change will allow us to use the most recent release of the `nmdc-schema` package as well, since that required python>3.9.

Update python and nmdc-schema

---

README.md
nmdc_server/app.py

Closes https://github.com/microbiomedata/issues/issues/19
This PR moves the API docs from "/docs" to "/api/docs".
Although references to "/docs" have been updated in the README.md, a [301 Moved Permanently](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301) response is added to the backend in case this is being referenced elsewhere.
Test this by:
- visiting "/api/docs" and ensuring the documentation is visible
- visiting "/docs" and ensuring you're redirected to "/api/docs"

Move documentation endpoint

---

nmdc_server/schemas.py

`annotations.depth` is now a dict which causes response validation to fail.

Allow `AnnotatedValue` to be a dict

---

nmdc_server/app.py
tests/test_app.py

Solves #825 
This is to improve the data portal's API compatibility with the reverse proxy set up to unify this API with the NMDC runtime API. Due to how FastAPI's documentation endpoint works, we needed to move where the openapi json schema was served from to ensure compatibility with the unified API.
Previously, [api-dev.microbiomedata.org/api/docs](api-dev.microbiomedata.org/api/docs) was serving the runtime API documentation, where it should be serving the data portal API documentation.
To Test:
- visit /api/openapi.json and make sure the schema is served from that endpoint.

Move location of openapi schema

---

nmdc_server/migrations/versions/9bbb32f36d19_context_address_form.py
nmdc_server/schemas_submission.py
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue
web/src/views/SubmissionPortal/store/api.ts
web/src/views/SubmissionPortal/store/index.ts

This PR holds the set of changes that persist submission portal data collected from the new context/address form. For more information on how that form integrates into the existing workflow, see [this diagram](https://lucid.app/lucidchart/75516c27-0974-4a77-ae92-73234e3f385e/edit?invitationId=inv_8fe7dca1-e52f-431c-9a0e-f1e6dd1e3a72&page=0_0#).
This PR contains changes to our pydantic models. Since attempting to load old data (without context/address form) would result in errors, a database migration that converts metadata submissions to be compatible with model changes is also included in this set of changes.

Persist facility, award, and shipping data

---

web/.eslintrc.js
web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextShippingForm.vue
web/src/views/SubmissionPortal/store/index.ts

This PR builds some front-end validation into the new context and address forms. Validation added in this PR is as follows:
**Context Form**
1. The "Has data already been generated for your study?" choice is required
2. If data has been generated, the DOI field is required (this field has been moved from the multiomics form)
3. If a facility (EMSL or JGI) is selected from the "Are you submitting metadata for samples that will be sent to a DOE user factility?" an award type is required
4. If the Award type is "Other," the associated text field must have a non-empty string
**Address Form**
1. Only show IRB fields if biosafety level is BSL2
**Additional Changes**
1. New `enums` for `BiosafetyLevels` and `AwardTypes`
2. Sample type drop down (address form) pulls in values from the NMDC schema

Context and address form validation

---

nmdc_server/migrations/versions/9bbb32f36d19_context_address_form.py
nmdc_server/schemas_submission.py
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/store/index.ts

https://user-images.githubusercontent.com/7085625/217668631-6f56e328-cc0b-4c53-b80f-fc0f84d0f51e.mp4
https://user-images.githubusercontent.com/7085625/217669626-c7b45e56-2aff-45c6-925e-9e3717ffcf0b.mp4
https://user-images.githubusercontent.com/7085625/217671513-8e10cd80-0889-4532-82f8-551a77b5d44d.mp4
This PR includes some other, minor updates, guided by notes on the [lucid chart.](https://lucid.app/lucidchart/75516c27-0974-4a77-ae92-73234e3f385e/edit?invitationId=inv_8fe7dca1-e52f-431c-9a0e-f1e6dd1e3a72&page=0_0#)
1. Removal of the arrow icon from the `v-combobox` component for alternate study names. Since we're not actually using this as an autocomplete with existing options, this arrow is just a confusing UI element
2. Removal of the NCBI project name field, in favor of just using the …

Use context form data to present different controls

---

web/package.json
web/yarn.lock

The latest version of the `data-harmonizer` package includes a fix to how it parses/formats multivalued slot values to/from delimited strings. This fixes a bug in the submission portal where rows with multiple values in the "analysis/data type" column would not be persisted across multiple DataHarmonizer tabs. 
The fix can be verified by:
1. On any submission portal entry, go to the DataHarmonizer screen. For any row select multiple values for the "analysis/data type" column. It should say, for example, "metabolomics; metagenomics" (note the space after the semicolon).
2. Click the "Validate" button
3. Verify that the "analysis/data type" cell you edited has not changed. It should still read "metabolomics; metagenomics" with a space after the semicolon.

Upgrade data-harmonizer library version

---

web/package.json
web/yarn.lock

No changes to functionality in this release. It is built in a new way that attempts to reduce the main bundle size.

Upgrade to data-harmonizer@1.4.6

---

web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts

Fixes https://github.com/microbiomedata/issues/issues/76
This handles an edge case that I missed in the original fix for that issue. Specifically, these changes ensure that the necessary fields are populated in the `sampleData` object even in the case where _no_ data has been entered in DH interface. To test: create a new submission, once you reach the DH screen click the "Download XLSX" button before any other interaction.

Fix XLSX export bug when entire DH is empty

---

web/src/App.vue
web/src/components/Presentation/AppHeader.vue
web/src/components/Presentation/AuthButton.vue
web/src/menus.ts
web/src/plugins/vuetify.js
web/src/views/Search/SearchHelpMenu.vue
web/src/views/Search/SearchLayout.vue

Related to https://github.com/microbiomedata/issues/issues/123.
These changes are mainly aimed at getting the portal's nav header to have similar organization and styling as the WordPress site's header. I don't want to close the issue with these changes because I'm sure there will be a few rounds of iterating on the exact content of the menus. Finally once that's all sorted out, I'll go back and update the WordPress header to ensure the content there matches.

Implement WordPress-style app bar

---

nmdc_server/ingest/all.py

This prevents trying to connect to a replicaset. See https://pymongo.readthedocs.io/en/stable/migrate-to-pymongo4.html#pymongo4-migration-direct-connection

Use `directConnection=True` for mongo client

---

nmdc_server/migrations/versions/7b9f5a789198_submission_schema_v1_0_0.py

This resolves a hasty merge that resulted in multiple head revisions.

Make migrations linear

---

web/src/views/Search/SearchLayout.vue

When we make a request for studies, we limit the number of results by utilizing `usePaginatedResults`. Eventually we'll actually want to add pagination to the study UI (#914), but for now, I'm increasing the limit to 50 to accommodate new studies that need to be ingested.

Increase study limit

---

web/src/views/SubmissionPortal/Components/SubmissionList.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/store/index.ts

Solves #835 
This PR makes some minor updates to the way submitting samples works in the submission portal. 
Namely, it attempts to start creating a set of valid submission statuses based on what will eventually be needed for the system. "In Progress," "Submitted- Pending Review," and "Complete" are the only statuses defined  here so far.
A new dialog window has been added to the workflow, as described in the linked issue. See the video for a short demo. (@mslarae13 take a look if you'd like before this goes into dev, and I can address any feedback you have)
https://user-images.githubusercontent.com/7085625/228962627-e26f2b79-83c8-49de-b60a-ea503ba44d18.mp4

Add Submitted- Pending Review status

---

web/src/data/api.ts
web/src/views/IndividualResults/StudyPage.vue

Client-side changes only. #911 added the column to our data model. This supports multiple gold IDs for a single study being displayed as linked on the study detail page.
Fixes #918

Display all GOLD links for a study

---

web/src/components/InvestigatorBio.vue

Problematic behavior:
https://user-images.githubusercontent.com/7085625/230164855-9b99683a-2eec-4fc7-972e-4df22c49a551.mp4
The `v-image` component wasn't getting re-rendered when the source changed, and since our source images have different sizes, this caused visual problems when switching between studies.
Adding `v-bind:key` to the `v-image` component forces a re-render whenever the value of the key changes.
Fixed:
https://user-images.githubusercontent.com/7085625/230165744-ac07c80d-29e4-44c9-a4df-54f63b550d71.mp4

Force re-render of image on url change

---

web/src/views/SubmissionPortal/store/index.ts

The `tabsValidated` object keeps track of which DH tabs have been validated. It is built from the `templateList`. Previously, if a template was removed from `templateList`, it would remain in `tabsValidated`, even though it could never be validated.
Fixes #936 
To test, perform the following steps using this branch and data-dev.microbiomedata.org.
1. Create a new submission
2. Choose No for "Data already generated", choose JGI (arbitrary, but JGI allows you to skip address form), and whatever project you'd like
3. Continue to Multi-omics form (enter whatever Study Information you want)
4. Select "Metagenome" and Metatranscriptome under JGI, enter a JGI ID
5. DESELECT metaT (or metaG, I don't think this matters)
6. Continue to the Data Harmonizer tab
7. Run validation for each tab
8. …

Keep better track of tabs to be validated

---

web/Dockerfile

Similar to #732, our client side build process was broken by recent pushes to the stable nginx image. Pinning to 1.22.

Pin nginx to 1.22 for client build

---

web/public/index.html

close #958 
Update website title to reflect that we are no longer in a pilot phase.

Remove "Pilot" from site title

---

web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/Components/StudyForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue
web/src/views/SubmissionPortal/Components/SubmissionDocsLink.vue
web/src/views/SubmissionPortal/Components/SubmissionList.vue
web/src/views/SubmissionPortal/Components/TemplateChooser.vue
web/src/views/SubmissionPortal/HarmonizerView.vue

fix microbiomedata/issues/issues/239
This PR creates a new component, `SubmissionDocsLink`, which simply provides an icon to be used as a link to documentation. The component has been added to each step of the submission portal with links to the corresponding section in the submission portal [user documentation](https://nmdc-documentation.readthedocs.io/en/latest/howto_guides/submit2nmdc.html).

Add submission portal documentation links

---

web/package.json
web/src/views/SubmissionPortal/HarmonizerView.vue
web/yarn.lock

This upgrades to the latest version of the submission schema, 7.6.0 (there was a change in the version numbering scheme to align the version numbers with the main schema, hence the large jump). Previously the `source_mat_id` column was used to link rows across different DH tabs. That slot is no longer required, so `samp_name` -- which is required and values must be unique -- is used instead.

Upgrade to submission schema 7.6.0

---

web/src/views/SubmissionPortal/HarmonizerView.vue

I _think_ this fixes #916. 
The code in the watcher callback is needed when switching tabs: new data is loaded into the DH instance and a few other DH options are optionally set. However, by watching `activeTemplateData` that callback is fired way too often. `activeTemplateData` is [computed](https://github.com/microbiomedata/nmdc-server/blob/29aa87698b082769a97faf7cd788c58bb3ab1468/web/src/views/SubmissionPortal/HarmonizerView.vue#L83-L88) from `sampleData` and `sampleData` is [updated](https://github.com/microbiomedata/nmdc-server/blob/29aa87698b082769a97faf7cd788c58bb3ab1468/web/src/views/SubmissionPortal/HarmonizerView.vue#LL139C15-L139C15) anytime a cell is edited. Most of the time these extra reloads are benign. But it seems like there are scenarios (I guess based on how wide the …

Eliminate unnecessary DH data refreshes

---

web/src/util.js

This removes null values from the gold classification tree. It is important to note that this effects all the tree and as such should be discussed further. We may need a more sophisticated solution instead of this all or nothing approach.

Handle null gold slots

---

Dockerfile

There appears to be an issue with newer releases of the base image we use. In particular, the postgres versions might be causing the issue.

Use older version of base image

---

.github/workflows/deploy.yml

In this branch, I modified the GitHub Actions workflow that updates deployments on Rancher, to do so in the new development environment instead of the old development environment.
I got that by following these steps (I came up with these steps via trial-and-error):
1. Visit Rancher and go to the relevant cluster
2. Open the web browser's DevTools, go to the "Network" tab, and clear the list of requests (if any)
3. Reload the web page
4. In the list of requests, find the request for `namespaces`
5. In that request, go to the "Preview" tab to see the response
6. In the response, find the `data` array and—in that array—the namespace whose `id` is `nmdc-dev`, and look at its `metadata.annotations`
7. Get the value of the annotation whose key is `field.cattle.io/projectId`
- In the old …

Update Rancher URLs to reference new development environment

---

nmdc_server/ingest/biosample.py

Previously, biosample collection dates without a month or year would not be ingested. This interpolates months/days as needed
Fix #999

Allow parsing less specific dates

---

web/src/components/Presentation/OrcidId.vue

This may or may not be required, so we should hold off until we know for sure.

Don't display "unauthenticated" next to ORCID IDs

---

nmdc_server/filters.py
nmdc_server/query.py

Fix #1002 
#991 did not properly update SQLAlchemy code to join `biosamples` through to `omics_processing` records, resulting in some cartesian products which reduced the functionality of aggregating on omics type.
Additionally study filtering was broken due to multiple references to tables in generated SQL code, so aliases are used for `biosample` and `omics_processing` in order to eliminate this error.
Now, searching using the data portal should be functional, and omics types aggregations and studies should update as expected.

Use aliased tables for study search

---

web/src/components/Presentation/AttributeList.vue

This appears to be a first. We are displaying some data on a detail page that doesn't directly come from the object itself. Because of this I opted to not use `AttributeItem`.
Now, when applicable, a new section appears on the biosample detail page that contains a list of related biosamples. This list is built by looking at related `omics_processing` records, and noting what additional biosamples are used as inputs to those.
Fix #1008

Add related biosample to detail page

---

web/src/components/DataObjectTable.vue
web/src/components/SampleListExpansion.vue
web/src/views/Search/SearchLayout.vue

Fix #975 (partial)
This PR adds related Biosample inputs to the search results page. That is, if workflows had multiple biosample inputs (e.g. a pooled sample was used as the input), it will be indicated in the data object data for those biosamples:
Note that this PR does not update the biosample detail page.

Indicate pooled sample inputs on `DataObjectTable`s

---

nmdc_server/query.py

Fix #1020 
This affects all uses of the `/study/search` endpoint.
The only change is the addition of an `order_by` call in the SQL alchemy for study results.

Sort study results by title

---

web/src/components/Presentation/AttributeItem.vue
web/src/components/Presentation/AttributeList.vue

Closes #1022 
Adds related biosample name to gui:
Also adds link to `study_id` attribute

Add related biosample name and link to study_id

---

web/src/components/SampleListExpansion.vue

partially handles #1023, this is admittedly an easy, incomplete fix
the button for expanding the data object table is disabled if there is no processed data.

1023 disable empty data tables

---

web/src/components/Presentation/AuthButton.vue

Fix #970 
This PR moves us closer to ORCID integration compliance by adding some information about how we intend to use users' ORCID IDs to the login workflow.
Now, if a user is logged out, hovering over the login button will display a modal that has some information about our use of ORCID.

Add ORCID integration info to login button

---

web/src/store/index.ts
web/src/views/IndividualResults/StudyPage.vue

Fixes #933 
**Previous Behavior:**
When on a study page, if a user clicked the sample count, they would be taken back to the main data portal view, and the study list would be filtered to show only the study they were just looking at. If the user clicked one of the omics processing chips, they would be taken back to the main data portal view, and the study would be selected (indicated by the checkboxes next to the study titles). If a study is further down the list, the visual cue would be missing.
See linked issue for screenshots
**New Behavior**
Now, both actions produce the same result: a returning to the main data portal view with only the study of interest present in the studies list. If the user wants to see all studies, they have to remove the filter from the search sidebar.

Unify behavior of study page filters

---

web/src/use/usePaginatedResults.ts

Fix results race condition

---

nmdc_server/app.py

`NMDC Dataset API` -> `NMDC Data and Submission Portal API`
@aclum @jeffbaumes any objections to this change? This affects the title at the top of the swagger page. I think the proposed title better reflects what the user is actually looking at. I am open to any tweaks as reviewers see fit.

Rename data portal API

---

nmdc_server/api.py
nmdc_server/cli.py
nmdc_server/crud.py
nmdc_server/database.py
nmdc_server/jobs.py
nmdc_server/query.py
web/src/components/FacetedSearch.vue
web/src/data/api.ts

Fix #965 
Fix #1071 
This PR adds some additional query options when using the text search bar, as well as establishes a framework for including more in the future. For this iteration, we have added plaintext searching for:
`title` of `Study`
`description` of `Study`
`name` of `Study`
In order to accomplish this, our DSL query language has been updated to support using the SQL `ilike` function. This was a straightforward change for properties represented directly as columns on the `study` table, but required some additional work for values stored in the `annotation` column (JSON).
There is also a new CLI command, `nmdc-server create-or-replace-nmdc-functions` which updates the custom NMDC functions used for ingest and search at a whim, rather than relying on the SQLAlchemy event system. …

Allow searching text for study name and description

---

nmdc_server/query.py

Fix #1072 
Each filter in our queries keeps track of what table it is applied to. For example, a filter on "PI Name" would apply to the `study` table. Our backend search layer often makes use of this information to build appropriate SQL queries.
One spot in particular is during the study search. Part of creating this query is updating the omics processing counts per study. This is what appears in the omics counts chips on the data portal in the study search results section.
Before this change, the omics processing counts were only updated if a search contained a filter on the `omics_processing` or `biosample` tables. A filter on the KEGG terms uses the `gene_function` table, so the counts weren't being updated based on that filter.
This change makes sure that filters on KEGG terms are …

Aggregate omics counts for gene function search

---

nmdc_server/query.py
tests/test_query.py

Fix #1085 
The SQL query generated by the `BaseQuerySchema` class has a problem when performing a query for a model with conditions that apply to related models.
In the linked issue, this manifested in incorrect `Study` results when multiple filters were applied to the `Biosample` model.
Now, `Study` search results are "sanity checked" against `Biosample` search results for queries that include filters on `Biosample`.
A new test was added to simulate the query described in the issue that validates this approach.

Filter on biosamples before studies

---

web/package.json
web/yarn.lock

Upgrading to the latest submission-schema. No changes required migration of existing submissions.

Upgrade to submission-schema 9.2.0

---

nmdc_server/api.py

I put "processings" in an attempt to pluralize the word "processing" (which I think is being used as a noun in this context).

Fix inaccuracy in API endpoint name

---

nmdc_server/cli.py
nmdc_server/config.py
nmdc_server/jobs.py

Re: https://github.com/microbiomedata/nmdc-server/issues/1079
These changes are in support of having a cron job in Rancher for periodic automated ingests. The idea is that cron job will use the existing `server` Docker image to do an ingest via the existing `nmdc-server` CLI. Typically when we initiate an ingest manually we do so via the API with a `POST /api/jobs/ingest` request. I'm proposing _not_ using the API for the automated ingest because 1) the `/api/jobs/ingest` endpoint requires authentication and that would be challenging without persistent API authentication tokens and 2) we would probably need to add an additional endpoint to check on the job status after is has been finished in order to poll for success or failure. 
The changes here move the guts of the `ingest` celery task …

Update ingest CLI to support scheduled ingest

---

nmdc_server/cli.py

Just a quick revision to #1103. I had been testing that locally against the "development" project (which we don't really use anymore). This updates the ingest CLI to use the correct endpoint for the "production" project where we used namespaced secrets.

Used namespacedSecrets endpoint to get/update rancher secrets in ingest

---

.github/workflows/deploy.yml

Fixes https://github.com/microbiomedata/issues/issues/554
These changes update the `deploy.yml` workflow file to:
* Tag Docker image with `main` for pushes to the `main` branch. Tag Docker image with `prod` and `X.Y.Z` for pushes to tags like `vX.Y.Z`. This is accomplished by using the `docker/metadata-action` action.
* Redeploy the Rancher `nmdc-dev` workloads on pushes to `main` and `nmdc` workloads on pushes to version tags. Previously only `nmdc-dev` workloads were redeployed on pushes to main. 
Once these changes are in place I'll update Rancher to point the `nmdc` workloads to the new `prod` tagged images. Then when a GitHub Release is created with a new version tag the deployment will happen automatically with no need to update anything in Rancher. This also brings this repository …

Reconfigure deploy workflow to use main/latest/version number Docker tags

---

nmdc_server/api.py
tests/test_app.py

- Implemented an API endpoint (`/api/version`) that returns the application version number
- Added a test targeting that endpoint
- Note: Most of the commits in this branch are related to linting
Screenshot showing that the API returns the same version number as Swagger UI shows:

Implement `/api/version` API endpoint that returns app version

---

nmdc_server/api.py
nmdc_server/auth.py
tests/test_submission.py

Fix #1113 
Since microbiomedata/nmdc-server#1098 introduced new FK relationship (`locked_by`) between the `submission_metadata` and `user_logins` tables, a join condition needed to be specified for SQLAlchemy, when joining those tables. This was not done in the submissions list endpoint, which broke it in development.
This change adds the join condition to `api.py::list_submissions` function, and adds a test. It also alters how `auth.py::admin_required` works. The `user.is_admin` check is no longer skipped in the `"testing"` environment. Existing tests were also updated to accommodate this change.

Specify join condition for submissions and users

---

.dockerignore
Dockerfile
docker-compose.yml

This is a follow-up to #1105. `setuptools-scm` uses the git working directory state as part of its [default versioning scheme](https://setuptools-scm.readthedocs.io/en/latest/usage/#default-versioning-scheme). So to get the right version number we need to ensure that the working directory is clean before `pip install`-ing the `nmdc-server` package. Two things were making it unclean:
* The base image (`tiangolo/uvicorn-gunicorn:python3.9-2023-06-05`) includes an `/app/main.py` file. It's not used in any way; it just had some placeholder hello world code. That file needed to be removed.
* I needed to copy _all_ the checked-in files into the `/app` folder. Since that includes the `.git` directory itself it no longer needs to be mounted. Unfortunately I think this will make the image size …

Ensure clean git working directory to get correct version number

---

nmdc_server/filters.py

Fix #1115 
This PR changes how subclasses of `BiosampleFilter` join to the `omics_procesing` table.
Previously, they didn't specify at all, so when a filter on an envo term was applied to a search on `omics_processing` records, there was a Cartesian product and no filtering was done.
Now, those subclasses that represent `<EnvoTerm>Filter`s use the `join_envo` function of the `BaseFilter` class to perform the join and correctly filter omics processing results.

Specify join for envo term when faceting omics_processing

---

.git-blame-ignore-revs
nmdc_server/filters.py
nmdc_server/ingest/pipeline.py
nmdc_server/migrations/versions/0a3edcd64e1f_add_study_image.py
nmdc_server/migrations/versions/0f87ba7add08_lock_submissions.py
nmdc_server/migrations/versions/11a7decdcc60_massive_identifiers.py
nmdc_server/migrations/versions/1de891717fc0_multivalued_dois.py
nmdc_server/migrations/versions/23e0702d2321_multi_tab_metadata_submission_format.py
nmdc_server/migrations/versions/60b8a4b0c60e_read_qc_nullables.py
nmdc_server/migrations/versions/780ab86a4f27_squashed_initial.py
nmdc_server/migrations/versions/7b9f5a789198_submission_schema_v1_0_0.py
nmdc_server/migrations/versions/7ba2cb5f236e_remove_gene_function_tables.py
nmdc_server/migrations/versions/86f42a05252b_ck_doi_format.py
nmdc_server/migrations/versions/9bbb32f36d19_context_address_form.py
nmdc_server/migrations/versions/ae7a3eba08c5_schema_v7.py
nmdc_server/migrations/versions/af8b2e3c91b2_biosample_omics_association.py
nmdc_server/migrations/versions/b51ae399d49f_add_gold_identifiers.py
nmdc_server/migrations/versions/b8f3bcb681a1_separate_emsl_ids.py
nmdc_server/migrations/versions/b96ecfffa792_remove_irb_information.py
nmdc_server/migrations/versions/dad555bb9212_submission_schema_v7_7_2.py
nmdc_server/migrations/versions/dcc0a41b60af_optional_file_size.py
nmdc_server/migrations/versions/de3d2eaa2a59_nullable_pi.py
nmdc_server/migrations/versions/ded8702fcc7a_submission_roles.py
nmdc_server/migrations/versions/eb9d9e3f3fbc_user_model.py
nmdc_server/migrations/versions/ffaec255fe68_swap_columns.py
nmdc_server/query.py
nmdc_server/schemas.py
nmdc_server/table.py

It looks like the `black` check is failing because it's picking up a new major version (24.1.1). This PR just reformats according to that version and adds the commit to the ignored revisions.

Reformat with black v24

---

web/package.json
web/src/components/MenuContent.vue
web/src/data/api.ts
web/src/views/SubmissionPortal/Components/StudyForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextShippingForm.vue
web/yarn.lock

Fix #1125 
Big jump 6.0.4 -> 10.0.0
We use this for facet descriptions in the search sidebar, and some enums and descriptions in the submission portal. 
The structure of the package directory changed, so the import statements were updated to match.

Update nmdc-schema for client app

---

.github/workflows/deploy.yml

Previously there was logic to try to resolve the differences between workload names in the dev and prod Rancher namespaces (e.g. `portal-backend` on dev and `backend` on prod). This logic was faulty and was a little opaque. These changes remove that logic and split the dev redeploy and prod redeploy into separate steps with appropriate `if` clauses. It's a little more verbose now, but at least it's more clear what it's doing. It also makes it simpler to add an additional step to redeploy the sandbox workloads as part of a production release.
Fixes #1121
Fixes #1122

Fix how Rancher workloads are redeployed in GitHub workflow

---

.github/workflows/deploy.yml

I recently "renamed" (i.e. replaced with workloads having different names) the targeted workloads on Spin.
In this branch, I updated the `deploy.yml` GitHub Actions workflow to use those new names.

Update URLs to reflect new workload names on Spin

---

web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts

Re: https://github.com/microbiomedata/issues/issues/412 (will close once it has been tested on dev)
These changes make a set of JGI-related columns read-only in DataHarmonizer. This does _not_ prevent the columns from being populated by importing an XLSX file. This is a feature, not a bug.
To test:
* Go to any submission with a JGI MG and/or JGI MT tab
* Enter data in the first tab to ensure that some rows will display in the JGI tab(s)
* On the JGI tab(s) ensure that the indicated columns cannot be edited

Make certain JGI columns always read-only in DataHarmonizer

---

nmdc_server/api.py
nmdc_server/crud.py
nmdc_server/ingest/pipeline.py
nmdc_server/models.py
nmdc_server/schemas_submission.py
tests/test_submission.py
web/.gitignore
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/Components/StudyForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextShippingForm.vue
web/src/views/SubmissionPortal/Components/TemplateChooser.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/StepperView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts
web/src/views/SubmissionPortal/store/api.ts
web/src/views/SubmissionPortal/store/index.ts

Close #1077 
Rounds out the initial batch of development to enable per-submission editor permissions.
Based on permission level of the currently logged-in user, submission forms and fields are locked down if appropriate.
- `owner`: this is the only permission level that can submit or edit PI Orcid. Additionally, owners can add a permission level (`viewer`, `editor`, `metadata_contributor`) for contributors on the Study form
- `editor`: can no longer click the Submit button or edit PI Orcid. 
- `metadata_contributor`: all forms except for the data harmonizer table are disabled.
- `viewer`: all forms including the data harmonizer are disabled.
Permission levels are checked for the `PATCH /metadata_submission/{id}` endpoint. Request bodies should not only include data that the logged in user …

Add permission level to study form

---

web/src/components/Presentation/AttributeItem.vue
web/src/components/Presentation/AttributeList.vue
web/src/data/api.ts
web/src/util.js

On the biosample details page, the depth is now displayed according to the following rules:
1. If the depth annotation contains a minimum, a maximum, and a unit → display `{min} - {max} {unit}`
1. If the depth annotation contains a minimum and a maximum (but no unit) → display `{min} - {max}`
1. If the depth annotation contains a magnitude and a unit → display `{depth} {unit}`
1. Otherwise → display whatever is in the top-level `depth` property
> Local URL: http://localhost:8081/details/sample/gold:Gb0110680
> Local URL: http://localhost:8081/details/sample/nmdc:bsm-11-q5nxet10
> Local URL: http://localhost:8081/details/sample/gold:Gb0115859
> Local URL: http://localhost:8081/details/sample/igsn:IEWFS000I
<details>
<summary>Developer notes for myself (click to show/hide)</summary>
Here's …

Show depth as range or with units, if possible

---

web/src/use/usePaginatedResults.ts

Closes #1034 
Adding a debouce to `fetchResults` when conditions change ensures that the desired query when copying a url is fired second and eliminates the race condition.

Add debounce to fetch results when conditions change

---

web/src/views/SubmissionPortal/Components/StudyForm.vue
web/src/views/SubmissionPortal/store/index.ts

Close #824 
This addresses some feedback about the new permission system for the submission portal. In particular, it:
1. Fixes a bug that prevented users with "metadata contributor" roles from saving submissions.
2. Hardens "editor" permissions by preventing "editor"s from deleting themselves as a contributor for a submission. It also prevents them from changing their own ORCID or deleting other contributors, since this may cause issues if those contributors had permissions themselves.
3. Add form validation to prevent multiple contributors with the same ORCID iD.

Fix multiple submission editors issues

---

nmdc_server/api.py
web/src/views/Search/SearchLayout.vue

Use annotation title for child studies if available.
Children studies whose parent isn't in the search results should only be included if they don't appear as a child in any other part study present in the search results.
You can check both issues by expanding `River Corridors Science Focus Area`. The correct title for the grow child study is `Creating the GROW...`. Also because grow appears here it should not appear as a top level study in the study results.

Grow Study fixes

---

web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/Components/StudyForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextShippingForm.vue
web/src/views/SubmissionPortal/Components/SubmissionPermissionBanner.vue
web/src/views/SubmissionPortal/Components/TemplateChooser.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/store/index.ts

Fix #1162 
Fix #939 ~~(temporary/non-ideal fix)~~
This PR addresses additional issues with assigning permissions from the UI and adds some UX enhancements like banners and tooltips.
If the same ORCID iD was used for the PI ORCID and as a contributor ORCID iD, then the permission level set at the contributor level had priority over the ideal PI level (`owner`). Now, priority is given to the `owner` role when building the request body to update the submission with new permissions.
~~This is a "fix" for #939. The address form now validates by investigating data in addition to through Vuetify's form validation. Vuetify's form validation was insufficient because the address form cannot be validated by it until it is opened. The previous workaround for this was to open the form, which would be …

Submission Permission fixes

---

nmdc_server/api.py
tests/test_submission.py

Fixes #1165 
* Adds a handler for `DELETE /api/metadata_submission/{id}` requests. I figured that only owners (or admins) should be able to delete submissions. I also erred on the side of caution in not allowing the delete if the submission is locked by someone. If you think that could be better let me know. 
* Sort of unrelated, but it would be really helpful to the Field Notes app if the submission list endpoint had a stable sort. I know there have been discussions in the past about full on sorting and filtering of submissions in the portal. But without getting into all that I thought it might be uncontroversial to just sort them by newest by default.

Add submission delete endpoint

---

web/src/menus.ts

In this PR branch, I updated the header menu of the Data Portal to match the header menu of the website.
Here's a screenshot showing how the two sites' menus compare at the highest level.
Here's a pair of screenshots showing how they compare at the next level down (only one example dropdown menu is shown here).
|Website|Data Portal|
|--|--|
| <img src="https://github.com/microbiomedata/nmdc-server/assets/134325062/a19ef15d-9284-4511-969e-c319eeb0a724" width="200" /> | <img src="https://github.com/microbiomedata/nmdc-server/assets/134325062/48eac93b-308f-4d4d-ba17-ae072afca1f0" width="200" /> |
---
**Tip for reviewer:** Here's a [JavaScript snippet](https://github.com/microbiomedata/nmdc-server/issues/1179#issuecomment-1986712709) you can copy/paste into a web browser's JS console while …

Update links in header menu to match website menu

---

web/src/menus.ts

In this branch, I switched from using the `to` property (which appears to me to have been designed for client-side routing only) to the `href` property (which appears to me to have been designed for server-side routing only). I also added some documentation about that difference in an attempt to make it less likely that someone make the same mistake in the future.
Fixes https://github.com/microbiomedata/nmdc-server/issues/1195

Fix navigation link URLs in "Resources" section

---

web/src/menus.ts

In this branch, I added an item to the "Productions" menu in the navigation bar, that points to a web page about the upcoming NMDC Field Notes mobile app. The same menu item was added to the website earlier today, causing the Data Portal's navigation menu and the website's navigation menu to fall out of sync. This PR brings them back into sync.

Add `Field Notes Mobile App` link to navigation menu

---

web/src/menus.ts

In this branch, I added an item to the "News & Impact" menu in the navigation bar, that points to a web page containing an archive of NMDC Newsletter editions. The same menu item was added to the website earlier today, causing the Data Portal's navigation menu and the website's navigation menu to fall out of sync. This PR brings them back into sync.

Add `Newsletters` link to navigation menu (to match website)

---

web/src/views/SubmissionPortal/Components/StudyForm.vue

Fix #1202
Fix microbiomedata/issues/issues/573
Previously if 2 contributors were added to the Study form of a submission and no ORCID iD was provided for either, the form wouldn't validate since those 2 contributors had the same ORCID. Now, empty ORCID fields are not checked for uniqueness.
To reproduce in prod:
1. Create a new submission. 
2. On the study form, add 2 contributors and fill in the name and Credit Role fields for each. 
3. Observe that you cannot go to the next page. Clicking into one of the blank ORCID fields will reveal the validation error
To test these changes (locally or in dev once this PR is merged):
1. Create a new submission. 
2. On the study form, add 2 contributors and fill in the name and Credit Role fields for each. 
3. Make sure you can navigate to the next …

Don't check empty ORCID iDs for uniqueness

---

docker-compose.yml
web/package.json
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts
web/yarn.lock

Fixes https://github.com/microbiomedata/submission-schema/issues/168
These changes add a new "Metagenome (Long Read)" checkbox to the Multiomics Data screen in the submission portal. If selected, it enables a new corresponding tab in the DataHarmonizer screen. It all works analogously to the existing checkboxes and tabs.
It turned out that once that was implemented, switching between the Metagenome tab and the Metagenome (Long Read) tab surfaced a bug in the version of Handsontable used by DataHarmonizer@1.4.7 related to column headers not being updated correctly. This bug was fixed in the version of Handsontable used by the latest version of DataHarmonizer. 
Upgrading from DataHarmonizer 1.4.7 to 1.6.5 actually corresponds to quite a large jump in Handsontable (7.4.2 to 13.1.0). Despite …

Add metagenomics long read option and logic to UI

---

web/src/components/AppBanner.vue

This PR branch includes three changes:
- A spelling error is fixed:
```diff
- Anouncement
+ Announcement
```
- Hyperlinks are no longer followed by an underlined space
- Makes the line height consistent throughout the banner (previously, first line differed)
Before:
After:

Fix spelling error and hyperlink formatting

---

web/src/components/AppBanner.vue
web/src/views/IndividualResults/SamplePage.vue
web/src/views/IndividualResults/StudyPage.vue
web/src/views/Search/SearchLayout.vue
web/src/views/SubmissionPortal/SubmissionView.vue
web/src/views/User/UserPage.vue

Add banner for re-iding

---

web/src/views/Search/SearchLayout.vue
web/src/views/Search/SearchSidebar.vue

Previously, while sample data was being loaded, the upper left of the page would say "Found 0 results". Similarly, the top of the "Samples" panel would say "0 Samples".
In this PR, I made it so that, while sample data is being loaded, the message in the upper left says "Loading results..." and the top of the "Samples" panel doesn't report a number.
> Note: The horizontal misalignment of the "Samples" (or "x Samples") heading with respect to the "Consortia" and "Studies" headings is not part of this PR (neither introduced in this PR nor fixed in this PR).

Refrain from reporting "0 results" and "0 samples" while loading data

---

web/src/components/AppBanner.vue

This branch is based upon the most recent release (i.e. the commit tagged `v0.20.0`) instead of being based upon the tip of the `main` branch.

Update banner to indicate new re-ID-ing date

---

.gitignore
docker-compose.yml
docs/development.md
nmdc_server/cli.py
prestart.sh
scripts/docker/init.sql

Fixes #1228 
* The main addition is the new `click` subcommand named `load-db` in `nmdc_server/cli.py`. This subcommand is designed to 1) get a list of available backups on NERSC in the `/global/cfs/cdirs/m3408/pgdump` directory, 2) make a local copy of the latest one (or a specified one), 3) run `pg_restore` on the _local_ database using the copied backup.
* I wanted to make sure that this workflow worked:
1. Completely destroy entire local Postgres database (or perhaps this is the first time ever running `nmdc-server`)
2. Run the new `load-db` command to populate the database
3. Run `docker compose up` to start the whole stack
The issue I ran into was that the `nmdc_a` and `nmdc_b` databases are currently being created in the script (`prestart.sh`) that runs just before the web server …

Add nmdc-server CLI subcommand for loading local database with production data

---

nmdc_server/api.py
nmdc_server/crud.py
nmdc_server/query.py

Fix #1176 
Adds some post-query logic the to `/biosample/search` endpoint that filters out `OmicsProcessing` records from the results.
The logic incurs the overhead of an additional database query, in order to determine which omics processing records are valid given the current filter conditions. Then each result populated from the [lazy loading](https://docs.sqlalchemy.org/en/20/orm/queryguide/relationships.html#lazy-loading) is checked against the filtered list.
We only add this penalty if the search conditions contain at least one filter for the `omics_processing` or `gene_function` tables. Other filters apply at the study and biosample level, and would not apply to omics processing records. Below is some data on the performance impact when applying a KEGG filter for various page …

Filter out irrelevant omics_processing results

---

web/src/views/Search/SearchSidebar.vue

Closes #1219 
- Adds Active query conditions section to the navigation prepend slot. This makes the section sticky while the rest is still scrollable
- Limits the height of this section to 50vh and overflow scrollable so that the use can always make additional selections

Make query conditions section sticky and max size to 50vh

---

nmdc_server/api.py

This PR is to update the github issue creation. 
Previously I had misunderstood that the IDs needed would be either JGI/EMSL OR Gold/NCBI but we want to track all of them.
This change checks to see if these ID fields are populated and if they are it adds them to the issue creation.

Allow Github issue creation to track all IDs

---

web/src/views/SubmissionPortal/HarmonizerView.vue

This PR changes the wording on the Submit button in the harmonizer view to say "Submitted" after submitting data instead of "Done"

Change "Done" to "Submitted"

---

.github/workflows/berkeley-image.yml

Triggers on pushes to protected branch `berkeley-schema-migration`. Builds images and tags them as related to the migration effort.

Add GH action to build berkeley schema images

---

web/src/components/Presentation/AppHeader.vue
web/src/views/SubmissionPortal/Components/SubmissionStepper.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts

Fixes https://github.com/microbiomedata/issues/issues/701
* Create a new submission portal entry or open an existing one that you can edit, just ensure that in Step 4 (Multi-omics Data) the Metagenome checkbox under JGI is selected
* On Step 6 (the DataHarmonizer screen), ensure there are at least ~100 rows are filled out with at least an ID and that they all have "metagenomics" filled out in the "analysis/data type" column
* Click on the "JGI MG" tab
* Verify that you can scroll to the bottom and see all rows
Previously we set a fixed height directly on the element (`#harmonizer-root`) where the DataHarmonizer instance is mounted. This was a bit janky because the `362px` offset is a bit too brittle to changes in surrounding elements _and_ it doesn't interact well with DataHarmonizer's …

Fix DataHarmonizer scrolling issue

---

web/src/components/Presentation/AuthButton.vue
web/src/data/api.ts
web/src/store/index.ts
web/src/views/Login/LoginPage.vue
web/src/views/SubmissionPortal/Components/LoginPrompt.vue

Fix microbiomedata/user_research#19
Enable passing a state parameter to `initiateOrcidLogin()`, which is encoded in the login request and persisted by the server during the login process.
This handles two workflows where the user would need to be redirected:
1. When clicking the normal login button (the one in the app bar) while navigated to any route containing `submission`
2. When clicking the "login" button that appears on the submission homepage
In those 2 cases, the string `submission` is passed to `initiateOrcidLogin()`.
When we return from the server during the login process, we can expect a `state` query parameter if we sent one up at the start of login. The `init` function now takes this as an optional parameter and handles it accordingly. The only value for `state` that is …

Redirect users to submission portal if logging in from submission portal

---

nmdc_server/api.py

Closes #1046 
Adds partial search for `id`, `title`, `name` and `description` for biosamples

Add biosample columns to partial search

---

nmdc_server/auth.py
web/src/data/api.ts

This came up in the discussion of an `nmdc-runtime` PR (https://github.com/microbiomedata/nmdc-runtime/pull/572). Even though we're not claiming to be a full OAuth 2.0-compatible authorization server, I had intended to remain close to the standard where possible. I think it was just an oversight that I had used `expires` instead of the [recommended](https://datatracker.ietf.org/doc/html/rfc6749#section-5.1) `expires_in` as a field in the `TokenResponse` class. 
Nothing in the front-end actually uses that value, so I think this is a fairly low-risk change. But I'd rather change it now before it hits production for the first time.

Rename `expires` to `expires_in` in TokenResponse

---

web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/store/index.ts

Fixes https://github.com/microbiomedata/issues/issues/736
Two small updates related to recent "show save indicator" work here.
1. In the recent work, the `onDataChange` function became async. However its invocation in `changeTemplate` was not awaited before invoking the `validate` function. Both `onDataChange` and `validate` modify the `tabsValidated` object. Once `onDataChnage` became async its changes to `tabsValidated` got applied _after_ (and therefore clobbering) the changes applied in `validate`. Instead of awaiting the call to `onDataChange`, however, the fix here is actually to just remove it entirely. I believe all the necessary state updates when changing tabs are handled sufficiently by `validate`. The call to `onDataChange` may have at one time been necessary but not anymore. …

Remove extraneous data update call when changing tabs

---

.github/workflows/server.yml
nmdc_server/app.py
web/.eslintrc.js
web/package.json
web/src/components/Presentation/AuthButton.vue
web/src/data/api.ts
web/src/plugins/router.ts
web/src/store/index.ts
web/src/store/localStorage.ts
web/src/views/User/UserDetailPage.vue
web/yarn.lock

Fixes #1277 
These changes add a new page served on `/user` that provides information about the currently logged-in user. For now this page is mainly to facilitate providing information about making authenticated API requests, but it could potentially be expanded in the future.
* The top of the new page displays the user's name and ORCID iD (linked to their ORCID profile). If they are an admin that is indicated next to their name.
* The new page's Developer Tools section allows a logged-in user to view and/or copy their existing Refresh Token and provides general instructions on how to use it in their application.
* The Swagger UI's header now has instructions for obtaining and using an Access Token
* The site header's auth button now links to the new User page instead of ORCID
* To show …

Add user info page

---

web/src/views/SubmissionPortal/Components/ContactCard.vue
web/src/views/SubmissionPortal/Components/SubmissionList.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/SubmissionView.vue

Adds a contact support panel on the DH page and submission list page. Should match the styling in [figma](https://www.figma.com/design/KUtfSqxhYCn334xkoh2CBr/Submission-Portal?node-id=2002-72&t=vxvDnJJq7VoXRkov-0).
Closes https://github.com/microbiomedata/user_research/issues/20

Add contact support panel

---

nmdc_server/migrations/versions/b6e2cb2f8f36_add_submission_source_client.py
nmdc_server/models.py
nmdc_server/schemas_submission.py
web/src/views/SubmissionPortal/store/api.ts

This is in support of https://github.com/microbiomedata/nmdc-field-notes/issues/128.
These changes add a `source_client` column to the `submission_metadata` table. The column is nullable and its type is an enum with our two "known" clients: the submission portal and the field notes app. All existing submissions are assumed to have come from the submission portal. A `null` value in this column would indicate the submission came from somewhere other than our two first-party clients. This should be something we keep an eye on, possibly included in the reports we produce for @mslarae13 when she goes hunting for submissions to delete.
These changes also update the corresponding frontend code to set the `source_client` to `submission_portal`. Other than that the new column isn't really used …

Add ability to track which client created a submission

---

nmdc_server/api.py
nmdc_server/crud.py
nmdc_server/schemas.py
tests/test_submission.py
web/src/plugins/router.ts
web/src/views/SubmissionPortal/Components/SubmissionList.vue
web/src/views/SubmissionPortal/StepperView.vue
web/src/views/SubmissionPortal/store/api.ts
web/src/views/SubmissionPortal/store/index.ts

These changes are in support of having the Field Notes app respect the `locked_by` field on `SubmissionMetadata` records (https://github.com/microbiomedata/nmdc-field-notes/issues/90). There are two issues I'm trying to address here:
1. The Field Notes app attempts to cache and reuse responses from `GET` requests whenever possible. The underlying assumption of the caching layer is that `GET` requests have _no_ side effects. Currently, however, a request to `GET /metadata_submission/{id}` may also modify the record being returned by updating the `locked_by` field.
2. The Submission Portal has a unified view/edit interface for `SubmissionMetadata` records, whereas the the Field Notes app allows you to view a `SubmissionMetadata` before allowing the user to navigate to a separate edit …

Add endpoint for explicitly requesting `SubmissionMetadata` lock

---

web/src/components/FacetedSearch.vue
web/src/encoding.ts
web/src/views/Search/SearchSidebar.vue

Changes the title of the search sidebar section from "ENVO" to "MIxS Environmental Triad"
Additionally, changes all search facet names in the sidebar to be title case.
Fix #1175

Use more descriptive section name for envo terms

---

web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts

Fixes #1306 
Despite its name, DataHarmonizer's `showColumnsBySectionTitle` method actually expects a section _name_, and we were passing it a section _title_. 
The map that was previously being used to drive the options (`schemaSections`) only recorded the section titles. That map has been renamed to `schemaSectionColumns` since it is a map from section title to and array of column information. Otherwise it is unchanged and still used in computing `fields`. 
To actually fix the bug, these changes add a map (`schemaSectionNames`) from section titles (for display) and section names (to pass to `showColumnsBySectionTitle`).

Pass correct string to showColumnsBySectionTitle when showing single section

---

web/src/views/SubmissionPortal/HarmonizerView.vue

Fixes #1304 
I think I got a little overzealous with using flexbox layouts in https://github.com/microbiomedata/nmdc-server/pull/1267, which resulted in this bug being introduced. 
These changes fix the issue by having the help sidebar container be absolutely positioned within its parent element. When toggling the sidebar open/closed a corresponding amount of padding is added to/removed from its sibling element which holds the DataHarmonizer instance. This is so that the sidebar doesn't cover the rightmost columns.
This approach is conceptually similar to the way it worked before https://github.com/microbiomedata/nmdc-server/pull/1267 except it uses absolute positioning instead of `float`. I find `float` has more unpredictable side effects, so I tend to avoid it.
Ensure that the help …

Fix DataHarmonizer help sidebar positioning

---

web/src/views/SubmissionPortal/Components/StudyForm.vue

Due to how Vuetify's [form validation](https://v2.vuetifyjs.com/en/components/forms/#usage) works by default, having validation rules that check mulitple values on a single form don't cause unchanged fields to revalidate. Thus, fields must revalidate the form when changed if they have dependant fields.
In this particular case, the ORCID field's validation state depends on the contributor permission level. So whenever a contributor permission level changes, we must revalidate the form to obtain the correct validation state of the ORCID fields.
[Observable in dev, prod, sandbox]
Adding a contributor to a submission's study form and filling out Name, Credit Roles, and permission level don't trigger validation for the ORCID field. The expected behavior is that once a permission level is …

Revalidate form when permission level changes

---

tox.ini

Fixes #1324 
As @JamesTessmer discovered in https://github.com/microbiomedata/nmdc-server/pull/1323, all versions of `types-pkg-resources` have been yanked from PyPI (see linked issue for details). This updates the `typecheck` testenv dependencies as needed.

Replace types-pkg-resources with types-setuptools

---

pyproject.toml

This resolves a security warning from dependabot.
Updates our dependency on `httpx` (`0.18.0 -> 0.23.0`), the minimum version to resolve the warning.
Please check out this branch and make sure the docker image builds and the app run as expected on your local machine.

Update httpx to 0.23.0

---

nmdc_server/data_object_filters.py
nmdc_server/ingest/all.py
nmdc_server/ingest/biosample.py
nmdc_server/ingest/omics_processing.py
nmdc_server/ingest/study.py
nmdc_server/schemas.py

Fix #1291 
This breaks the ingest process for any version of `nmdc-schema` version `<11.0.0`. For deployments of the NMDC Data Portal using this code base and ingest, ingest must be pointed at a database that conforms to the "[Berkeley Schema](https://github.com/microbiomedata/berkeley-schema-fy24)"
This set of changes updates ingest to be able to accept data from a source mongo database running version `>=11.0.0` of the NMDC Schema (Berkeley). It does not attempt to update the data portal in any other way. From and end-user perspective, the changes here should have no impact. Users should see the same data, presented in the same way as data ingested from an older version of the mongo database. It does not attempt to rename endpoints, files, classes, functions, or variables to be up to …

Berkeley schema ingest

---

docs/development.md

Recent changes mistakenly removed the close of a code block.

Close code block

---

web/src/components/FacetedSearch.vue
web/src/encoding.ts
web/src/views/Search/SearchLayout.vue
web/src/views/Search/SearchSidebar.vue

Replace instances of "omics," "omics type", etc. with the appropriate Berkeley language (e.g. "Data Generation"). Applies to user-facing places to the data portal only.
See the issues for the specific requests. Changes include:
- The tab for the bar chart on the home page changed ("Omics" -> "Data Type")
- The search sidebar facet section changed ("Omics Processing" -> "Data Generation")
- The search sidebar facet changed ("Omics Type" -> "Data Type")
Fix #1326

Replace Omics with Data Generation

---

nmdc_server/api.py
nmdc_server/fakes.py
nmdc_server/schemas_submission.py
web/src/definitions.ts
web/src/views/SubmissionPortal/Components/StudyForm.vue
web/src/views/SubmissionPortal/store/index.ts

@mslarae13 @pkalita-lbl 
This PR adds some small changes to the `funding_source` description to point towards and example. 
I figure if we also want to make the `funding_source` box accept multiple values we can add that change here as well.

Update funding source entry text box and description

---

nmdc_server/api.py
nmdc_server/schemas.py
tests/test_app.py

This is part of https://github.com/microbiomedata/nmdc-field-notes/issues/156
These changes add the `nmdc-schema` and `nmdc-submission-schema` version identifiers to the response of the existing `/api/version` endpoint.
⚠️ Quasi-breaking change ⚠️ 
The response used to contain the key `nmdc-server`. I changed it to `nmdc_server` along with adding new keys that also use underscores instead of dashes. This makes it easier to deal with in both Python and JavaScript/TypeScript code. I don't _think_ there are any existing clients of this endpoint, but if anyone is uncomfortable with that change let me know.

Add schema version identifiers to /api/version response

---

web/src/menus.ts

In this branch, I added a new menu item to the navigation bar; specifically, I added a menu labeled "Data API", which links to the Runtime API's Swagger UI. Regarding why the name "Data API" was used, you can refer to [this conversation](https://github.com/microbiomedata/nmdc-server/issues/1330#issuecomment-2297711714) (the gist is that some people thought the word, "Runtime," would not be meaningful to people outside of our team).
Fixes https://github.com/microbiomedata/nmdc-server/issues/1363

Add "Data API" link to navbar ("Products" menu)

---

nmdc_server/aggregations.py
nmdc_server/schemas.py
web/src/components/BulkDownload.vue
web/src/data/api.ts

Fix #1344 
Modifies the query used by the `/data_object/workflow_summary` endpoint to include a sum of the sizes of the data objects at the workflow type and file type level. Updates the frontend to display these sizes (if non-zero) in the bulk download control
Check out the new labels for the tree view in the bulk download control! They also show up when you select file types to add to the bulk download:

Show per-workflow and per-filetype sizes in bulk download

---

nmdc_server/crud.py
nmdc_server/query.py
nmdc_server/table.py
web/src/components/FilterKegg.vue
web/src/encoding.ts

Fix #1342
This updates the KEGG facet to allow users to search for pathways terms using prefixes other than `map`. Supported prefixes for pathway searches now include `ko`, `ec`, and `rn` in addition to `map`. 
We store pathway terms in the `ko_term_text` table in postgres, all with the `map` prefix. In order to support searching on these terms we do some string substitution so that users can use whichever prefix they'd like. 
This affects free-text search for the KEGG facet on the frontend. If a user types in a term that begins with one of the prefixes associated with a pathway search, the associated backend code (`crud.py::kegg_text_search`) will interpret that as a request to search for pathways, making sure the results keep the the prefix that the user wanted. For example, a user …

Support pathway search with multiple prefixes

---

web/src/components/Presentation/UpSet.vue

closes #1044 
The numbers for the upset bar chart are now clickable and should return the same results as the bar improving usability for the smaller values.

Add click functionality to numbers

---

pyproject.toml

Part of https://github.com/microbiomedata/submission-schema/issues/220
v11.0.0rc1 is the first release candidate version of `nmdc-submission-schema` to be built off of a Berkeley release candidate of `nmdc-schema` (specifically v11.0.0rc20). Very little of the Berkeley changes in `nmdc-schema` affect `nmdc-submission-schema` so I wouldn't expect any major issues here. I tested this locally by viewing the DataHarmonizer screen of a submission (something seems wrong with the `/submission/{id}/context` route in the `berkeley-schema-migration` branch, but I could manually go to the `submission/{id}/samples` route) and doing some basic data entry and validation.

Upgrade to nmdc-submission-schema v11.0.0rc1

---

web/src/components/FacetedSearch.vue
web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue

Just two quick fixes for places where the frontend code was tripping over some Berkeley schema changes:
* `web/src/components/FacetedSearch.vue`: The `gold_path_field` slot does not have the referenced annotation in the Berkeley schema. The change to add the annotation was merged into `nmdc-schema` on [July 17](https://github.com/microbiomedata/nmdc-schema/pull/2120) and the last time `berkeley-schema-fy24` was synced with `nmdc-schema` it included changes through [July 16](https://github.com/microbiomedata/berkeley-schema-fy24/pull/229). So the annotation should come back eventually. In the meantime this prevents a render-time error.
* `web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue`: We just needed to refer to the enum's new name.

Fix Berkeley schema element usage in frontend code

---

nmdc_server/migrations/versions/317274ad8137_add_cog_mappings.py

A hotfix introduced a new migration between the development and final review/ merging of the COG ingest changes, which resulted in a revision tree with multiple heads. In this state, Alembic does not know how to proceed and so deployments of the data portal were not starting up correctly.
Fix #1386 
Linearizes the Alembic migration files. The two migrations in particular are completely separate, so there's no conflict to resolve within the migrations themselves.
Note: see #909 for a similar situation and resolution

Change down_revision of COG table migration

---

nmdc_server/api.py
tests/test_submission.py

In this branch, I updated the `/metadata_submission/report` API endpoint so that the TSV file it generates includes two additional columns: "Source Client" and "Status". I also updated the test that targets that endpoint so it asserts that those columns contain the values I expect.

Update submission report to include "Source Client" and "Status"

---

nmdc_server/api.py
tests/test_app.py
web/src/data/api.ts

Fix #1394 
Update the public-facing endpoints in the "omics_processing" group to use "data_generation" instead. 
The scope of this change is limited to updating those API endpoint URLs only, and makes sure that corresponding code on the client uses the new route names. It does not attempt to scrub the phrase "omics_processing" from this code base. That is a much larger task that is outside the scope of the "MVP" release of the Berkeley schema.

Rename omics_processing endpoints to data_generation

---

nmdc_server/ingest/study.py

Fix #1406 
Updates ingest to pull study protocol URLs out of the correct slot. A potential follow-on task post rollout has been added to #1331

Use correct slot for study protocols for Berkeley schema

---

nmdc_server/alembic.ini
nmdc_server/cli.py
nmdc_server/ingest/all.py
nmdc_server/jobs.py
nmdc_server/migrations/versions/e54d37bfb90b_rename_data_object_workflow_types.py

Fixes #1415 
The primary goal of these changes is adding the new Alembic migrator `nmdc_server/migrations/versions/e54d37bfb90b_rename_data_object_workflow_types.py`. The `upgrade` function modifies the values in the `workflow_type` column of the `data_object` table in accordance with changes to types introduced by the Berkeley schema refactor.
But isn't the `data_object` table truncated at the start of the ingest process? Yes, it is. But after the main `load` step of the ingest, there are three calls to `maybe_merge_download_artifact` which merge records from the live database back into the ingest database. Since those records have relationships to `DataObject` records, old values can leak back in. 
These changes also fix some issues around logging that prevented the informative …

Migrate `workflow_type` values in `data_object` table

---

web/src/components/AppBanner.vue
web/src/views/IndividualResults/SamplePage.vue
web/src/views/IndividualResults/StudyPage.vue
web/src/views/Search/SearchLayout.vue
web/src/views/SubmissionPortal/SubmissionView.vue
web/src/views/User/UserDetailPage.vue
web/src/views/User/UserPage.vue

In this branch, I hid the banner and reset its content with placeholder content.
I already deployed this to production via a hotfix (release `Release 2024.10.1` / tag `v1.0.1`). I'm opening this PR because the final step of our internal [Developing and releasing a hotfix](https://github.com/microbiomedata/infra-admin/blob/main/releases/nmdc-server.md#developing-and-releasing-a-hotfix) guide says to open a PR to merge the hotfix branch into `main`.

Hide banner about Berkeley Schema Roll Out downtime, and reset its content

---

nmdc_server/ingest/kegg.py

Fix #1385 
Explicitly skip BRITE hierarchy terms that don't have any children.
The data portal uses a JSON blob from https://www.genome.jp/kegg-bin/download_htext?htext=ko00001&format=json to populate its tables of KO terms. It appears as though this file contains KO terms grouped by Brite hierarchies. Ingest code appears to anticipate this, and does not add rows for parent nodes that don't have children.
This is a problem since there is one parent node without children that we want to skip, since we don't support the full Brite hierarchy at this time. This new change handles the issue by safeguarding against this specific case.

Skip BRITE terms

---

web/nginx.conf.template
web/src/views/SubmissionPortal/HarmonizerView.vue
web/start.sh

Fixes #1444 
These changes address two items exposed by a user attempting to save a large set of sample metadata:
1. The save request was being rejected because of nginx's maximum payload size setting
2. The UI was not telling the user that the request failed
First, the [`client_max_body_size`](https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size) directive has been added to the nginx config template. It is populated with the value of the `NGINX_CLIENT_MAX_BODY_SIZE` environment variable. If this variable is not set manually, it will get set to `10m` via `web/start.sh`. This will allow payload sizes of 10 MB (the default is 1 MB). We can also choose to set the `NGINX_CLIENT_MAX_BODY_SIZE` in Rancher if we need to adjust the value on the fly for whatever reason. …

nginx payload size config and sample metadata loading indicator

---

nmdc_server/ingest/all.py
nmdc_server/ingest/pipeline.py

This PR includes changes to ingest. Until upstream data is migrated to include the [schema changes](https://github.com/microbiomedata/nmdc-schema/pull/2203) that necessitated this change, ingest will fail to create records based on `functional_annotation_agg`s
The slot that links `functional_annotation_agg` members to their `workflow_execution`s has been changed to be `was_generated_by`. This change is now reflected in ingest code.
Make sure ingest populates the ____GeneFunctionAggregation tables.

Use correct slot when querying gene aggregations

---

nmdc_server/ingest/kegg.py
web/src/components/FilterGene.vue

Fix #1450 
Fix #1451 
Fix some bugs that prevented KEGG orthologs and modules, and COG pathways from being ingested.

Properly ingest ko terms and COG pathways

---

.env.example
nmdc_server/cli.py
nmdc_server/config.py

In this branch, I updated the ingest CLI script so that, when it finishes a successful run, **if a Slack incoming webhook URL is defined**, the script uses that URL to post a message to a Slack channel. This technique for posting messages to Slack is documented [here](https://api.slack.com/messaging/webhooks).
Outside of this PR, I have created a Slack app and—for that Slack app—generated an incoming webhook URL. That is what I plan to use on Spin (in all of our environments) once this code gets deployed there. For any reviewers that intend to test this locally, I can also provide that URL to you via Snappass (or Spin). Using that specific URL, the Slack message will be posted to the newly-created `#ingest-notifications` channel in the NMDC Slack workspace.

Post message to Slack when ingest completes successfully

---

nmdc_server/api.py
nmdc_server/crud.py
tests/test_submission.py

Add a script to api.py and a query to crud.py to pull information from the submission portal database, and then generate a report of NMDC submissions that have been submitted as a TSV. 
This PR references issue 2047 in nmdc-schema: https://github.com/microbiomedata/nmdc-schema/issues/2047

Implement API endpoint that returns TSV report about submissions that are pending review

---

nmdc_server/migrations/versions/4aee1e10bb24_add_nmdc_edge_source_client.py
nmdc_server/models.py
web/src/views/SubmissionPortal/store/api.ts

Fixes #1469 
This addresses a request from NMDC EDGE developers who are working on functionality to create submission records from the EDGE interface (https://github.com/microbiomedata/nmdc-edge/issues/103).

Add `nmdc_edge` as a permissible `source_client` value

---

nmdc_server/data_object_filters.py
web/nginx.conf.template

Resolve data object ingest errors where data objects are skipped if their URL is not one of the whitelisted domains for the NMDC data portal.

Add additional data proxies

---

web/src/use/usePaginatedResults.ts
web/src/views/SubmissionPortal/Components/SubmissionList.vue
web/src/views/SubmissionPortal/store/api.ts

This PR is linked to issue: https://github.com/microbiomedata/issues/issues/826
The goal is to add a delete submission button inside an overflow menu that could be added to later.
Clicking the delete button will show a confirmation menu, and when confirmed the submission will be deleted from the front-end schema.

Add delete submission button and overflow menu

---

web/src/views/SubmissionPortal/HarmonizerView.vue

Closes https://github.com/microbiomedata/issues/issues/968
Concerns https://github.com/microbiomedata/issues/issues/767
This allows users to submit samples without providing an e-mail. This is an interim fix until we create a UI/UX improvement for this feature

Allow users to submit without an email stored for their account

---

nmdc_server/api.py
nmdc_server/schemas_submission.py

This is a bit of follow on work to the changes for #1367.
These changes allow a client to create a new submission using _either_ a list of strings or single string for the `packageName` field. The reason for this comes down to the fact that the release cycle for the Field Notes app is decoupled from the `nmdc-server` release cycle (by necessity, due to app store review delays). 
The app already knows how to deal with `packageName` values _coming from_ the server that are either string _or_ lists of strings. But when creating a new submission, the app doesn't know _a priori_ whether the server will accept a single string or an array of strings for the `packageName`. We will release an update to the app to make it send an array of strings by default, but it will take a little bit of time to …

Allow creating a submission with string or list of strings for `packageName`

---

nmdc_server/database.py
nmdc_server/ingest/omics_processing.py
nmdc_server/multiomics.py
web/src/components/Presentation/UpSet.vue
web/src/components/SampleListExpansion.vue
web/src/data/api.ts
web/src/encoding.ts
web/src/views/Search/BiosampleVisGroup.vue
web/src/views/Search/SearchLayout.vue

Fix #1464 
Incoming `data_generation` documents with an `analyte_category` of `"lipidome"` are now ingested correctly, and the associated fields in postgres, including the `multiomics` bitmap are populated with that in mind. (The bitmap used for type now uses 6 bits instead of 5).
Added Lipidomics as a new category and updated the bit manipulation on the frontend to makes sure the "multiomics" facet works with lipidomics.
Previously there were explicit filters in front end code that prevented display of lipidomics data. These have been removed. As a result, lipidomics now appear in the bar chart, the flyout for the Data Generation type facet, and as a drop-down in the biosample result section.

Support Lipidome Results

---

web/src/components/TeamInfo.vue
web/src/data/api.ts
web/src/views/IndividualResults/StudyPage.vue

Fix #1493 
This issue and PR will likely be associated with a hotfix in order to fix the issue straightaway on production. Upon approval of this PR I intend to follow the standard procedure and create a tag from the HEAD of this branch to use as the hotfix version.
@aclum does a hotfix sound like the right thing to do for this issue?
Straightforward and simple guardrail added to handle `null` values for a study's `funding_sources`.
Obtain a copy of the most recent data. With your local docker stack up, running
```bash
docker compose run backend nmdc-server load-db -u <nersc-username>
```
will prompt you for your password + MFA key (or you can create/use an ssh key, read the help for that command for some additional details). Once authentication succeeds you will get a copy of the most …

Guard against null `funding_sources`

---

nmdc_server/data_object_filters.py
nmdc_server/ingest/all.py
nmdc_server/ingest/pipeline.py
nmdc_server/query.py

Fix #1496 
Closes #1468 
Special logic for gene function search wasn't being applied in all cases. Additionally, there were issues with ingesting MetaP gene function annotations that are resolved here, including a slight change to the data model on the mongo side. Further work should be done to remove the `best_protein` column from our database.
Since the initial change is intended to be a hotfix, I am leaving out any data model changes to keep scope and complexity at a minimum. That progress will be tracked in #1484

Fix metap ingest

---

web/src/views/Search/BiosampleVisGroup.vue

Fix #1501 
Previously, the legend for the upset plot used hard-coded string values to map abbreviations to data type. There is already an object being used as a dictionary to map abbreviations to data type. This PR removes the hard-coded `<span>`s in favor of using the existing object.
It also fixes the issue where the label on the upset plot for lipidomics didn't match the key in the legend.

Use same object for tooltips and legend

---

nmdc_server/api.py
nmdc_server/config.py
web/src/components/AppBanner.vue
web/src/data/api.ts
web/src/store/index.ts

Fix #1439 
The application settings, as defined in `config.py` contain two new variables:
- `portal_banner_title`: an optional string that determines the title of the banner that appears on the data portal when the team needs to communicate to users
- `portal_banner_message`: an optional string that holds the content of the banner
These two settings default to `None` and have been added to the `/settings` endpoint so they can be retrieved by the client.
Two new `ref`s have been added to the store to track the app banner title and message.
In the `init` function (defined in `src/store/index.ts`), a request is made to the `/settings` endpoint. The response from this endpoint is used to populate the new refs. This function is called when the Vue App is mounted, and during the login flow.
The …

Use environment variables to populate Data Portal banner

---

nmdc_server/fakes.py
nmdc_server/migrations/versions/18127fd43a8b_add_country_to_shipper_info.py
nmdc_server/schemas_submission.py
web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextShippingForm.vue
web/src/views/SubmissionPortal/Components/SubmissionContextShippingSummary.vue
web/src/views/SubmissionPortal/store/api.ts
web/src/views/SubmissionPortal/store/index.ts

Closes #1281 
Included in this PR
- An additional user input regarding if the samples will be shipped (EMSL)
- Adds the 'country' field to the shipping info
- Makes _only_ the country field required
- Adds a tooltip explaining that the sender's info is needed and updates help text

1281 update shipping info

---

nmdc_server/ingest/omics_processing.py
web/src/components/DataObjectTable.vue

Fix #1514 
On ingest of `data_generation` records, there is now an additional check to see if slots `has_mass_spectrometry_configuration` and `has_chromatography_configuration`. In the case that one or both of those slots is populated, we'll do an additional lookup to the `configuration_set` collection in mongo, and store the `id` and `name` of the `configuration` document in the `annotations` column of the `omics_processing` table.
They are stored in the `annotations` blob as:
- `mass_spectrometry_configuration_name`
- `mass_spectrometry_configuration_id`
- `chromatography_configuration_id`
- `chromatography_configuration_name`
Storing these fields in the json blob has the advantage of not needing to update our database model. Our search already handles lookups into the `annotations` …

Display LC/MS Configurations for Lipidomics and Metabolomics

---

nmdc_server/crud.py
nmdc_server/ingest/data_object.py
nmdc_server/query.py

If a data object selected for bulk download had a file size of `NULL` or `0` (both perfectly valid NMDC data objects according to the [schema](https://microbiomedata.github.io/nmdc-schema/DataObject/)), we would include it in the file list for [mod_zip](https://github.com/evanmiller/mod_zip) like so:
```
-  data/object/url/...
```
This is not valid, per, mod_zip's documentation, and was preventing people from executing bulk downloads including these files.
Construction of the file list for mod_zip has been changed. Files whose `file_size_bytes` is `NULL` or `0` are no longer included. Additionally, we log a warning.
This is a hotfix. This branch was created from v1.3.0 (the January 2025 release). Normal hotfix procedure includes issuing a new tag to use for the production deployment at …

Hotfix: Don't include invalid data objects in mod_zip file list

---

nmdc_server/app.py
nmdc_server/database.py

This adds the SQLAlchemy panel to the debug toolbar which should let us view the queries executed in development.
Example:

Add SQLAlchemy panel to debug toolbar

---

docker-compose.yml
nmdc_server/app.py
nmdc_server/cli.py
nmdc_server/database.py
pyproject.toml

This adds a custom logging solution instead of using the builtin `echo` setting of SQLAlchemy. This lets us interpolate the SQL parameters, add indentation, syntax highlighting, timing, and the caller.
Before:
---
After:

Improve SQL logging output in development

---

web/src/encoding.ts
web/src/views/Search/SearchSidebar.vue

Fix #1517 
Adds UI for filtering by Mass Spec configuration and Chromatography configuration. The new facets are grouped under "Data Generation" like so:
Each of these facets allows users to select from a list of configuration names:
Note that these screenshots are from my local development environment, so any counts could be out of sync with the data currently available in mongo.
@kheal adding you as a reviewer to catch anything that might be off in the screenshots before this gets merged into dev for testing.

Add facets for mass spec and chromatography configs

---

web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/Components/StudyForm.vue

Closes #1370 
Allow required fields to show up with a red box and required message without first needing to click on the field, like this: 
Do this for:
- funding sources
- contributors
- JGI project ID
- EMSL project ID

Address empty fields not being marked as invalid

---

web/src/views/SubmissionPortal/Components/FindReplace.vue
web/src/views/SubmissionPortal/Components/HarmonizerSidebar.vue
web/src/views/SubmissionPortal/Components/MetadataSuggester.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts
web/src/views/SubmissionPortal/store/index.ts
web/src/views/SubmissionPortal/types.ts

Re: #1513 (will keep that issue open until #1512 is completed as these changes are going into that branch)
Currently the logic to determine which tabs should be shown in the final Submission Portal screen is encapsulated in the `getVariants` function in `web/src/views/SubmissionPortal/harmonizerApi.ts`. There's really no reason for that logic to live there; it is unrelated to the `HarmonizerApi` class. These changes:
* Move the logic of selecting which tabs to display (`templateList`) to `web/src/views/SubmissionPortal/store/index.ts`.
* Expand the logic to take into account the new questions asked by the combined submission context / multi-omics form.
* Make `HarmonizerApi` the default export of `web/src/views/SubmissionPortal/harmonizerApi.ts` and update existing imports accordingly. …

Add logic for showing sequencing data tabs

---

nmdc_server/api.py
nmdc_server/crud.py
web/src/views/SubmissionPortal/Components/SubmissionList.vue
web/src/views/SubmissionPortal/store/api.ts

This PR will update the `GET api/metadata_submission` endpoint to support filtering and add front end changes to allow users to filter submissions on the portal.

Add ability to filter submissions based on submission type

---

web/src/views/SubmissionPortal/Components/DataTypes.vue
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue

This is follow-on work to #1581 in order to finesse some of the validation logic of the multiomics form.
1. These changes ensure that we ask about non-user facility metagenome and metatranscriptome sequencing data, the compatibility questions are truly required. The gist of the fix is to add `:rules` to the relevant radio groups and to revalidate the form as new elements are added to it. I also updated the logic so that the answers the the "data compatible" and "data interleaved" questions are cleared when the related checkbox is unchecked.
| Before | After |
| --- | --- |
| <img width="1284" alt="image" src="https://github.com/user-attachments/assets/5a75dcad-469f-4aaa-a400-e8a1d12edc5b" /> | <img width="1284" alt="image" src="https://github.com/user-attachments/assets/857540d1-8b80-4908- …

Fix multiomics form validation

---

web/src/views/SubmissionPortal/HarmonizerView.vue

Resolves https://github.com/microbiomedata/nmdc-server/issues/935
This PR makes a small change to the data harmonizer to fix the above bug.
The screenshots below show the effect, the choice of column visibility is preserved through tab swap.
The only change was adding another call to `harmonizerApi.changeVisibility`, the hard part was figuring out where to add it.

Add fix for data harmonizer column visibility bug

---

nmdc_server/migrations/versions/cf73ba2f0f85_merge_context_multiomics.py
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue

Fixes #1596 
In the original implementation of the migrator for the merger of the context form and multiomics form, a few existing fields got dropped in the process. 
These changes update the migrator to:
* Carry forward the `awardDois`, `ship`, and `unknownDoi` fields from context form to multiomics form.
* Remove the reference to `datasetDoi`, which was removed from the context form some time ago (and replaced by `awardDois`).
* Attempt to populate the new multiomics form field (`doi`) based on existing data. 
I am editing the existing migrator instead of creating a new one because a new migrator wouldn't be able to recover fields from the `pop`'d `contextForm` field if it ran after this one.
The changes in `web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue` are because …

Update multiomics form merge migrator to account for all remaining and new fields

---

web/src/components/Presentation/AttributeItem.vue
web/src/encoding.ts

Closes https://github.com/microbiomedata/nmdc-server/issues/1024
Add hyperlinks to environmental context terms on the biosample pages.
Change the environmental context term icons from 'mdi-text' to 'mdi-link'.
Examples:
https://data.microbiomedata.org/details/sample/nmdc:bsm-11-6qgwc522
https://data.microbiomedata.org/details/sample/nmdc:bsm-11-jxa03j76
hyperlink for ENVO:00000446
https://www.ebi.ac.uk/ols4/ontologies/envo/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FENVO_00000446
hyperlink for PO:0025025
https://www.ebi.ac.uk/ols4/ontologies/po/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPO_0025025
hyperlink for UBERON:0035118
https://www.ebi.ac.uk/ols4/ontologies/uberon/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0035118

1024 add env context term links

---

nmdc_server/crud.py

Fix #1584 
When building the file list for `mod_zip`, we now skip including data objects whose value of `file_size_bytes` is `None`. These files result in lines in the file list that look like:
```
- None file://url/for/file path/for/file/in/zip/folder
```
This is invalid for `mod_zip`. We can't omit size information, as that is needed to create the zip archive, so we won't include the file, and we'll log a message to the `fastapi` server logs indicating that we've skipped the file.

Skip bulk downloading data objects without file size info

---

web/Dockerfile

These changes avoid the rebuild of nginx to add the mod_zip module. As noted in the comments, we lost the ability to rebuild nginx 1.22. That's because nginx decomissioned the Mercurial repo which was required for the build process. 
These changes implement a very short-term bandaid of basing the `nmdc-server/client` image off of the last stable `nmdc-server/client` version -- which already has nginx built with mod_zip.
Thanks for the suggestion @aclum! It's a wild one, but it works.

Avoid nginx rebuild by basing nmdc-server/client image off static older image

---

nmdc_server/api.py
nmdc_server/schemas_submission.py

Fixes #1622 
These changes exchange one Field Notes-related shim with another. The old one (regarding `packageName` as either a string or array of strings) is no longer needed because Field Notes has caught up with that change.
The new one allows Field Notes to continue providing the `GOLDStudyId`, `NCBIBioProjectId`, and `alternativeNames` fields in `multiOmicsForm`, as opposed to `studyForm`. Field Notes doesn't actually collect these values, but the backend enforces that at least empty strings/arrays are provided at creation time. That is why this shim (like the last one) is only needed in the `POST /api/metadata_submission` handler.
This is ready for review now. I'm keeping it as a draft to remind myself to make a hotfix tag from this branch before merging it into `main`.

Allow Field Notes to submit the old submission data model until its next release

---

.github/workflows/server.yml
docker-compose.yml

The official postgres docker image can be run with the first class services feature. See also
https://docs.github.com/en/actions/use-cases-and-examples/using-containerized-services/creating-postgresql-service-containers.
This PR also upgrades CI to use postgres 13 to match the docker-compose setup.

Remove third party postgresql-action from CI workflow

---

docker-compose.yml
nmdc_server/api.py
nmdc_server/config.py
nmdc_server/crud.py
nmdc_server/data_object_filters.py
nmdc_server/ingest/data_object.py
tests/conftest.py
tests/test_download.py
web/Dockerfile
web/nginx.conf.template

Fix #1587 
Previously, our bulk download feature relied on an nginx plugin called [mod_zip](https://github.com/evanmiller/mod_zip). We have decided to try and move away from mod_zip, due to its need for file size information and trouble building with newer nginx releases. Due to previous experience with [zipstreamer](https://github.com/scosman/zipstreamer), we have decided to try using that as a replacement.
The default `docker-compose.yml` file has an additional service: zipstreamer. It is a microservice written in Go that can be used to build and stream a zip file given a list of URLs. Note that we will need to update the Rancher deployments to include this new service so that zip download works when this PR lands.
Replacing mod_zip with zipstreamer was fairly plug-and-play. The major …

Use zipstreamer for bulk downloads

---

pyproject.toml
web/package.json
web/yarn.lock

On this branch, I updated the `nmdc-schema` and `nmdc-submission-schema` dependencies to version `11.7.0` (of each one). I also updated two LinkML-related dependencies to versions that are compatible with `nmdc-schema` version `11.7.0`.
Fixes #1636

Update `nmdc-schema` and `nmdc-submission-schema` each to version `11.7.0`

---

nmdc_server/jobs.py
nmdc_server/models.py

Fix #1586 
Our postgres database contains tables that can be split into 2 main categories:
1. Tables populated via ingest (e.g. `biosample`)
2. Tables containing persistent data (e.g. `user_logins`)
This structure is non-trivial to support due to the fact that some of our persistent tables refer to rows (via foreign keys) in the "ingest" tables. These tables are important, because they track down load statistics. 
For a quick refresher on ingest, the first step is to call a custom function called `truncate`.
https://github.com/microbiomedata/nmdc-server/blob/55fe8daa6c7603244f6a382edde38aa937ddc0f7/nmdc_server/database.py#L177-L199
Then, tables in category (1) are populated using `pymongo`.
One of the last steps is to merge the active database with the ingest database.  We have an A/B …

Exclude data objects from the merge process

---

web/src/plugins/router.ts
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/Components/SubmissionStepper.vue
web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/store/index.ts

Currently step 4 on the stepper is labeled 'Environment package' with the subtext 'choose package type'.
This no longer matches the page's heading and subtext, so this PR changes the text in the stepper to match.
There is no related issue for this change.
Before:
After:

Fix name and subtext in submission stepper

---

web/src/components/EcosystemSankey.vue
web/src/views/Search/EnvironmentVisGroup.vue

Fixes #1575 
There were two things causing this issue. 
1. The chart was not big enough to show all of the nodes and links of the data. 
- Solved with a responsive chart height based on the amount of data and implemented a min height
3. The Sankey chart uses a diminishing color scheme for the data links and the links quickly become 'invisible'
- Solved by creating a substantial array of colors to minimize the shade diminishing

Update link colors to use an array and adjust chart height for better visibility

---

nmdc_server/api.py

I added two pieces of information to the logs
- the ZIP file descriptor (so we know what the backend is asking of ZipStreamer)
- the chunk number (to help us communicate with one another)

Also log the ZIP file descriptor and chunk number (to help with debuging)

---

nmdc_server/api.py

This could be a workaround for some of the zipstreamer issues we've been seeing in dev.
Some error logs showed a `httpx.ReadTimeout` error. This change will stop `httpx` from throwing these errors.

Force no timeout for zipstreamer

---

nmdc_server/config.py
nmdc_server/crud.py

cc @shreddd 
Here is my idea for specifying an alternative host for data hosted at NERSC. We can use this to see if it makes any difference with zip download performance with zipstreamer.

Allow specifying a host for NERSC data

---

web/package.json
web/public/index.html
web/public/manifest.json

I updated the JavaScript package name from `nmdc-pilot` to `nmdc-server` (to match the repo name). Other names that I'd be OK with include `nmdc-server-web-client` and `nmdc-portal-web-client`, for example.
I updated the `<noscript>` error message from saying `nmdc-pilot` to saying `this web application`. I also removed the "[We're sorry but](https://en.wikipedia.org/wiki/Non-apology_apology)."
Finally, I updated the PWA application name from `App` to `NMDC` (to match the HTML document title).
We can discuss with the product owner the topic of updating the HTML document title (and the PWA application name) to say something more descriptive than `NMDC` (I don't know the history of that string being used there).

Remove references to `nmdc-pilot` in configuration files and error messages

---

nmdc_server/app.py
nmdc_server/cli.py
nmdc_server/static_files.py
start.sh
tox.ini

Fix #1486 
Only generate once before the app starts up, and mount normally as part of application startup. This change prevents multiple workers from all trying to generate the same static directory.

Centralize generating static content

---

web/src/views/SubmissionPortal/HarmonizerView.vue
web/src/views/SubmissionPortal/harmonizerApi.ts

Fix #947
(Use this spreadsheet for testing: [nmdc_sample_export.xlsx](https://github.com/user-attachments/files/20679377/nmdc_sample_export.xlsx))
While investigating the linked issue, I noticed 2 behaviors that this PR seeks to change.
When a user fills out a submission, the templates (tabs) that show up on the data harmonizer page are determined by the choices made at earlier steps. If a user's submission information results in tabs `A, B, C` showing up on the data harmonizer page, and imports a spreadsheet file that has worksheets for `A, B, C, D`, all of those templates would be imported, resulting in  sample data on the submission that was hidden to the user. Since template choice is locked in when any sample data is populated, users wouldn't be able to go back and add a tab to see …

Don't import worksheets if not selected

---

docker-compose.yml

Fixes https://github.com/microbiomedata/nmdc-server/issues/1676
I believe this should fix the issue causing the PostgreSQL database to be exposed on the LBNL network when spinning up the docker stack onsite at LBNL. Can confirm the stack still works as expected with this change.

Explicitly host the postgreSQL database on localhost

---

web/src/views/SubmissionPortal/HarmonizerView.vue

resolves https://github.com/microbiomedata/issues/issues/1209
To summarize the issue, currently if you validate a facility tab and then add data to another tab that populates those tabs their validation status doesn't update, even if the data added to those tabs is invalid, and you can submit.
This sets the validation status of facility tabs to false when a change is propagated to them from another tab.

Fix validation checking for environment tabs

---

.gitignore
web/src/data/protobuf-descriptor.json

fixes #1683 
To fix the issue found in #1683 the field 'name' and the operator 'like' needed to be added to the protobuf descriptor. 
While testing I realized the 'description' and 'title' fields were both missing as well. It appears as though all other operators are accounted for.

1683 fix name filtering

---

web/src/components/Presentation/FacetBarChart.vue
web/src/components/Presentation/SearchResults.vue

Fixes #1081 
This addresses an issue causing the border corners to be clipped by a pixel in the bar chart and search results. The bar chart issue is fixed by adding a wrapper element to the chart and hiding its overflow. The search result issue is fixed by ensuring the `v-list` bottom borders also have a border radius of 4px to match the wrapping panel.

Fix bar chart and search results containers border cutoff

---

tests/test_app.py

The `test_api_summary` function was testing two different endpoints together, `/api/summary` and `/api/stats`. This PR separates that test into two. The summary test is also improved now to test both the success of the response and the shape of the data by comparing it to the expected `DatabaseSummary` fields.

Refactor API summary and stats test to be two independent tests

---

nmdc_server/filters.py

The association tables used for joining during gene function search are not SQLAlchemy models, so the columns are not accessible as properties.

Fix column access during gene search

---

nmdc_server/query.py

We'll need to take care when joining between `omics_processing` and workflow tables. Right now we only have a facet for metaproteomics analysis category. As we add more facets, I'd recommend trying to generalize the approach started by this PR.

Use new association tables for facet counting

---

nmdc_server/api.py
web/src/data/api.ts
web/src/views/Search/SearchLayout.vue
web/src/views/User/UserPage.vue

This PR resolves https://github.com/microbiomedata/nmdc-server/issues/1673
New code here adds a search box to the Users page to allow filtering based on name or ORCID.
If something matching the ORCID RE pattern is entered into the box then it will search for that, otherwise it defaults to user name.
@naglepuff I haven't done any real formatting on the search box to make it look nice, I was hoping for an initial bit of feedback on functionality before that. Mostly I was wondering if we wanted something like a toggle button to filter based on admin status.
Examples:

Add search functionality for users table

---

nmdc_server/migrations/versions/0cb677fa8d5e_update_jgi_submission-schema_slot_names.py
pyproject.toml
web/src/views/SubmissionPortal/HarmonizerView.vue

Fixes #1722 
These changes upgrade to `nmdc-submission-schema` v11.10.0-rc.1. That version introduces a number of slot name changes (summarized in https://github.com/microbiomedata/submission-schema/pull/347). The accompanying migrator changes existing submission data to match. Finally, there was one place where a few of the renamed/removed slots were referenced in front-end code, and those have been updated as well.

Upgrade to nmdc-submission-schema v11.10.0-rc.1

---

web/src/components/DataObjectTable.vue

Fixes a bug that prevents data object tables from opening if the corresponding data generation has no `sampled_portions` key in its `annotations`.

Add optional chaining operator for sampled_portions

---

nmdc_server/api.py
tests/test_download.py
web/src/components/DataObjectTable.vue
web/src/data/api.ts

Fix #1707 
A new API endpoint has been added to allow a client to obtain the URL for specific types of data objects. This is necessary because the existing endpoint is only accessible to authenticated (i.e. _logged in_) users. The Krona plot's HTML needs to be accessible for all users. Being logged in should not be required to view these data objects. 
This endpoint accepts a `data_object_id` and returns the URL for the HTML for that data object only if the data object has a specific `file_type`. If this endpoint is used to try and obtain the download URL for a non-Krona plot data object, it return a `400`. Tests have been added for this endpoint.
Krona plots are now viewable on the data portal without the need to log in or click the download button. They are accessible by clicking the …

Make Krona plots viewable in data portal

---

web/src/encoding.ts

Fix #1739 
Updates the `MultiomicsValue` object, which maps different data types (e.g. `MB` for metabolomics) to the corresponding bit in the `multiomics` bitmask used by the data portal for searching and displaying the upset plot.
This PR adds "Amplicon" and adjusts the bitmasks for the other data types accordingly.

Fix multiomics bitmask

---

nmdc_server/ingest/omics_processing.py
web/src/components/AmpliconObjectDataTable.vue
web/src/components/SampleListExpansion.vue

Shows amplicon slots on data table instead of processed data info, since there is no processed data.

Amplicon fix

---

mypy.ini
nmdc_server/aggregations.py
nmdc_server/api.py
nmdc_server/cli.py
nmdc_server/crud.py
nmdc_server/database.py
nmdc_server/filters.py
nmdc_server/ingest/envo.py
nmdc_server/ingest/kegg.py
nmdc_server/ingest/omics_processing.py
nmdc_server/ingest/search_index.py
nmdc_server/ingest/study.py
nmdc_server/jobs.py
nmdc_server/models.py
nmdc_server/query.py
pyproject.toml
tests/conftest.py
tox.ini

Fixes #1697 
To perform the migration from SQLAlchemy 1.4 to SQLAlchemy 2.0, I followed the official [migration guide](https://docs.sqlalchemy.org/en/21/changelog/migration_20.html). To briefly summarize the steps taken, see the "commits" tab of this PR. 
The bulk of the process involved turning on warnings for features that were added/removed/changed between v1.4 and v2.0, and addressing each of those warnings one at a time, until `tox -e py312` stopped logging SQLAlchemy-related warnings. This process has been preserved by the commit history of this branch, so it is recommended to review it sequentially.
There may be some confusion about the removal of the `mypy` plugin for `SQLAlchemy`, and the decision to revert that change. SQLAlchemy 2.0 now provides a …

Migrate to SQLAlchemy 2.0

---

web/src/components/SampleListExpansion.vue

Resolves #1023 
Adds a tooltip to the disabled omics buttons (buttons where `omics_data` is empty) that explains why the button is disabled. The tooltip displays:
> Workflows have not been processed yet. Please contact [support@microbiomedata.org](mailto:support@microbiomedata.org) if you have questions.
It is implemented to close with a delay so that a user can hover outside of the button to click the email link inside the tooltip.

Add tooltip to disabled omics buttons

---

web/src/views/SubmissionPortal/Components/DataTypes.vue
web/src/views/SubmissionPortal/Components/ExternalProtocolForm.vue
web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
web/src/views/SubmissionPortal/store/index.ts

This fixes a state bug that was seen on dev. Also this splits out the `DOI/URL` field into two fields.
Testing steps:
1. Create a submission and proceed to the Multiomics Form.
2. Choose 'yes' to question 1 (Have data already been generated for your study?)
3. Choose 'non to question 2 (Was data generated at a DOE user facility (JGI, EMSL)? )
4. The External Protocol forms should appear as expansion panels for the following data types: Metaproteome, Metabolome, Natural Organic Matter (FT-ICR MS), Lipidome.
5. Fill out a couple of forms on different data types and ensure they update separately.
*Note*
- There are 3 types of External protocol; Sample Preparation Protocol, Data Acquistion Protocol and Data Access
- You should expect to see two fields for URL and DOI
- Sample Preparation …

Ms protocol fix

---

docs/development.md
docs/local_ingest.md

Adds information about how and why to run an ingest from a local copy of the mongo data.

Add local ingest documentation
