web/src/views/DatabaseSummary.vue
=> Update summary page

nmdc_server/api.py, nmdc_server/schemas.py
=> Fix bugs querying pipeline objects

web/src/data/api.ts, web/src/encoding.js, web/src/plugins/store.ts, web/src/util.js, web/src/views/IndividualResults/AttributeList.vue, web/src/views/Search/Search.vue, web/src/views/Search/Sidebar.vue
Partial fix for #51 -- still need profile pic
=> Support new data types in client

web/src/data/api.ts, web/src/plugins/store.ts, web/src/views/DatabaseSummary.vue
Here's how the homepage should look after this merges.  cc @jbeezley
=> Use DB Stats for generation of stats page

web/.eslintrc.js, web/src/App.vue, web/src/components/Presentation/ConditionChips.vue, web/src/components/Presentation/FacetedSearch.vue, web/src/components/Presentation/FloatFilter.vue, web/src/components/Presentation/Study.vue, web/src/data/api.ts, web/src/plugins/store.ts, web/src/views/Search/MenuContent.vue, web/src/views/Search/Sidebar.vue, web/tsconfig.json
=> Adds float and number range picker

web/src/components/Presentation/ConditionChips.vue, web/src/components/Presentation/FacetedSearch.vue, web/src/views/IndividualResults/AttributeList.vue, web/src/views/Search/Sidebar.vue
Fixes an error with chip conditions when you're on a type page and have conditions from another type.
fixes #71 too
=> Bugfix chips

web/src/data/api.ts
@subdavis Feel free to merge if it doesn't conflict with your branch.
=> Fix search endpoint for pipeline tables

web/src/components/Presentation/Study.vue
=> Fix study page PI image

web/src/components/Presentation/Study.vue
=> Fix citations and title on study page

nmdc_server/aggregations.py, nmdc_server/api.py, nmdc_server/crud.py, nmdc_server/schemas.py, tests/test_app.py, web/src/components/Presentation/EcosystemSankey.vue, web/src/data/api.ts, web/src/views/Search/Search.vue
=> Use server-side aggregation for sankey chart

web/package.json, web/src/components/Presentation/ConditionChips.vue, web/src/components/Presentation/DateFilter.vue, web/src/components/Presentation/DateInput.vue, web/src/views/Search/MenuContent.vue, web/yarn.lock
=> Filter for dates

nmdc_server/aggregations.py, nmdc_server/api.py, nmdc_server/crud.py, nmdc_server/schemas.py, tests/test_app.py, web/src/components/Presentation/LocationMap.vue, web/src/data/api.ts, web/src/views/Search/Search.vue
=> Use server-side aggregation for map view

create_database.py, nmdc_server/fakes.py, nmdc_server/models.py, nmdc_server/schemas.py, web/src/components/Presentation/Study.vue
=> Add a doi column to studies

web/src/plugins/store.ts, web/src/views/Search/MatchList.vue
=> Show zeros for unseletable field options

web/src/components/FacetChart.vue, web/src/components/Presentation/ConditionChips.vue, web/src/views/Search/MatchList.vue, web/src/views/Search/Search.vue, web/src/views/Search/Sidebar.vue
fixes #88 
fixes #98 
fixes #99
=> Minor fixes

web/src/util.js
=> Ignore missing type information in typeWithCardinality

web/src/components/Presentation/FacetedSearch.vue
=> Fixes #106 #107

web/src/views/IndividualResults/AttributeList.vue, web/src/views/IndividualResults/IndividualResults.vue, web/src/views/Search/ConditionChips.vue, web/src/views/Search/Sidebar.vue
=> Solve 106 properly

.github/workflows/deploy.yml
The server will go down for about 30s while the database is repopulated.  At some point, we will need to start using migrations to chase those 9's.
=> Enable automatic deployment on push to master

nmdc_server/api.py
@jbeezley these endpoints were broken into different sections, took me a second to notice that the facet and search were elsewhere.
=> Fix DO tags

nmdc_server/api.py
Until we implement auth, it's probably best to leave out the ability to delete entities.
=> Comment out DELETE endpoints

web/src/components/Presentation/FacetedSearch.vue, web/src/encoding.js, web/src/views/Search/Search.vue
fixes #123 
also fixes sorting within groups.
=> Fix #123 remove bar and pie charts

web/src/components/DataObjectsList.vue, web/src/components/FacetChart.vue, web/src/components/FacetSummaryWrapper.vue, web/src/components/Presentation/FacetChart.vue, web/src/data/api.ts, web/src/plugins/store.ts, web/src/views/IndividualResults/IndividualResults.vue, web/src/views/Search/Search.vue
=> Show context in FacetChart

web/src/components/Presentation/EcosystemSankey.vue
Makes sankey a little simpler and more generic.  If we had an endpoint, it would be pretty easy to make a different sankey for ENVO terms.
=> Make sankey code a little cleaner

Dockerfile, nmdc_server/auth.py, setup.py, tests/test_auth.py
Fix a few small issues that came up in deployment of the latest version.
=> Fix minor deployment issues

web/src/components/DataObjectsList.vue, web/src/components/Presentation/EcosystemSankey.vue, web/src/components/Presentation/SearchResults.vue, web/src/plugins/store.ts, web/src/views/Search/Search.vue
=> Server-side rendering

create_database.py, nmdc_server/aggregations.py, nmdc_server/api.py, nmdc_server/app.py, nmdc_server/auth.py, nmdc_server/errors.py, nmdc_server/models.py, nmdc_server/query.py, nmdc_server/schemas.py, tests/test_app.py, tests/test_query.py
This was for backwards compatibility with the web client that is no longer necessary.
=> Simplify the queries by making table name required

README.md, web/src/App.vue, web/src/components/Presentation/Auth.vue, web/src/data/api.ts
Add kinda trivial auth button.
@jbeezley review requested for small README addition.
=> Add authentication to client

web/src/views/Search/ConditionChips.vue
=> container tweak

nmdc_server/query.py
Use literal annotations to differentiate between condition schemas rather than custom validator logic.
=> Add better validation for query conditions

web/src/components/Presentation/DateHistogram.vue, web/src/components/Presentation/FilterList.vue, web/src/mixins/FacetSummary.js, web/src/views/Search/Search.vue
=> Add Date Histogram

create_database.py, nmdc_server/fakes.py, nmdc_server/models.py, nmdc_server/schemas.py
=> Add collection_date to the biosample schema

nmdc_server/query.py, tests/test_app.py
This adds an explicit condition type to be used for queries on the Gold environment hierarchy.  ~~It looks like this:~~
```
{
"table": "biosample",
"field": "gold_tree",
"op": "tree",
"value": {
"ecosystem": ["ecosystem 1", ...],
"ecosystem_category": ["category 1", ...],
"ecosystem_type": ["type 1", ...],
"ecosystem_subtype": ["subtype 1", ...],
"specific_ecosystem": ["specific ecosystem 1", ...]
}
}
```
~~In this implementation, the query it produces is an "OR" of all individual attributes (even between distinct attributes).  This would not be possible under the existing query schema because all filters on distinct attributes are combined with an "AND".~~
~~I *think* this is the most logical way to implement the desired behavior, but I would be interested hearing @subdavis's opinion …
=> Add a condition schema for tree queries on gold terms

create_database.py, migrations/env.py
=> Upsert data on ingest and trigger migrations

web/src/components/FacetSummaryWrapper.vue, web/src/components/Presentation/FacetBarChart.vue, web/src/components/Presentation/FacetHistogramChart.vue, web/src/mixins/FacetSummary.js, web/src/views/Search/Search.vue
=> client histograms

web/package.json, web/src/components/FacetSummaryWrapper.vue, web/src/components/Presentation/DateHistogram.vue, web/src/components/Presentation/FacetHistogramChart.vue, web/src/components/charts/ChartContainer.vue, web/src/components/charts/Histogram/Histogram.vue, web/src/views/Search/Search.vue, web/yarn.lock
It lacks a certain finesse, but it has potential.   Tooltips and better labels for the range slider would be nice.
fixes #172
=> Add D3 Histogram

web/src/components/Presentation/DateHistogram.vue
=> Reset slider when collection date query changes

web/src/views/Search/Search.vue
=> Add histogram for read qc

README.md, migrations/versions/8f03f0fac12b_initial.py, migrations/versions/9da3cb811a0e_mga_gene_functions.py, nmdc_server/fakes.py, nmdc_server/models.py, nmdc_server/schemas.py, prestart.sh, scripts/create_database.py, tests/test_app.py, tox.ini
This only adds the gene function schema.  It is missing the ingest scripts and the ability to query by gene function.
=> Add metagenome annotation gene function models

nmdc_server/fakes.py, nmdc_server/ingest/all.py, nmdc_server/ingest/pipeline.py, nmdc_server/migrations/versions/4aefb685cd39_mags_analysis.py, nmdc_server/models.py, nmdc_server/schemas.py
This only adds the schema and ingest.  I'll come back to adding all of the analysis types to the queries later.
=> Add MAGs analysis activities

nmdc_server/crud.py, nmdc_server/models.py, nmdc_server/query.py, nmdc_server/schemas.py, tests/test_query.py
This add the new types to the table summary and study search responses.  It also allows filtering conditions based on these tables.
I didn't yet implement querying these new tables as top-level entities (new api endpoints, e.g. `/metabolomics_analysis/search`).  Not sure if those endpoints are even needed with the new web client.  If so, I can add them easily.  It is just a lot of boiler plate.
=> Add new workflow activities to query api

web/src/components/Presentation/FacetedSearch.vue, web/src/components/Presentation/FilterList.vue, web/src/components/Presentation/SearchResults.vue, web/src/components/Presentation/Welcome.vue, web/src/encoding.ts, web/src/v2/components/MenuContent.vue, web/src/v2/use/usePaginatedResults.ts, web/src/v2/views/Search/BiosampleVisGroup.vue, web/src/v2/views/Search/Layout.vue, web/src/v2/views/Search/Sidebar.vue, web/src/views/Search/Sidebar.vue
Includes some of the changes requested.  More to come.
=> UI Progress, enable more search terms, enable more vis

web/src/data/api.ts, web/src/v2/components/DataObjectTable.vue, web/src/v2/components/SampleListExpansion.vue
fixes #236
fixes #234
fixes #233
=> various ui changes

web/package.json, web/src/components/Presentation/Auth.vue, web/src/main.ts, web/src/v2/components/DataObjectTable.vue, web/src/v2/components/SampleListExpansion.vue, web/src/v2/store/index.ts, web/src/v2/views/Search/BiosampleVisGroup.vue, web/src/v2/views/Search/Layout.vue, web/src/v2/views/Search/Sidebar.vue, web/yarn.lock
=> Download button

nmdc_server/api.py, nmdc_server/database.py, nmdc_server/ingest/lock.py, nmdc_server/jobs.py, nmdc_server/migrations/versions/15fee92ce478_add_ingest_lock.py, nmdc_server/models.py
=> Add an endpoint to start an ingest from mongo

web/src/components/Presentation/FilterList.vue, web/src/components/Presentation/FilterTree.vue, web/src/data/studyExample.json, web/src/views/Search/Search.vue
fixes #254 
Adds a 2 second delay on the appearance of progress indicators to avoid being overly noisy.
=> Progress for facets

scripts/requirements.txt, scripts/upset.py, web/src/components/Presentation/DateHistogram.vue, web/src/components/Presentation/UpSet.vue, web/src/v2/views/Search/BiosampleVisGroup.vue
Summary script for getting upset data.  No reason not to hang onto random scripts like this.
Results:
```
Sample Counts
metagenome 42
lipidomics_proteomics_metabolomics_metagenome 33
organic matter characterization_metatranscriptome_lipidomics_metagenome 40
organic matter characterization_metatranscriptome_metagenome 3
metatranscriptome_metagenome 2
organic matter characterization_lipidomics_metagenome 3
lipidomics_proteomics_metabolomics 1
organic matter characterization 34
Study counts
metagenome 2
lipidomics_proteomics_metabolomics_metagenome 1
organic matter characterization_metatranscriptome_lipidomics_metagenome 1
organic matter characterization_metatranscriptome_metagenome 1
metatranscriptome_metagenome 1
organic matter characterization_lipidomics_metagenome 1 …
```
=> Add summary script

web/src/plugins/router.js, web/src/v2/use/useClockGate.ts, web/src/v2/views/Search/BiosampleVisGroup.vue, web/src/v2/views/Search/EnvironmentVisGroup.vue, web/src/v2/views/Search/Layout.vue
Much smoother visualization loading
=> clock gate

web/src/components/Presentation/EcosystemSankey.vue, web/src/components/Presentation/FacetBarChart.vue, web/src/components/Presentation/LocationMap.vue, web/src/data/api.ts, web/src/encoding.ts, web/src/v2/components/AttributeList.vue, web/src/v2/components/FilterStringLiteral.vue, web/src/v2/views/IndividualResults/IndividualTitle.vue, web/src/v2/views/IndividualResults/SamplePage.vue, web/src/v2/views/IndividualResults/StudyPage.vue, web/src/v2/views/Search/BiosampleVisGroup.vue, web/src/v2/views/Search/Layout.vue, web/src/views/IndividualResults/AttributeList.vue
fixes #241 
fixes #293
fixes #275
fixes #292
=> More minor fixes

web/src/data/api.ts, web/src/v2/components/DataObjectTable.vue, web/src/v2/components/DownloadDialog.vue, web/src/v2/views/IndividualResults/IndividualTitle.vue, web/src/v2/views/IndividualResults/StudyPage.vue
fixes #230 
fixes #290 
fixes #298
=> ToS and RAW

web/src/v2/components/DataObjectTable.vue
=> File missing handle properly

web/src/components/Presentation/UpSet.vue, web/src/v2/components/DataObjectTable.vue
Also remove descriptions from API, leave blank if they weren't provided.
fixes #297
=> remove raw, fix upset titles

web/src/App.vue
Merge whenever it's safe to do so.
fixes #316
=> Href back to homepage

nmdc_server/ingest/biosample.py
=> Replace underscores in envo id's with colons

nmdc_server/query.py, tests/test_binning.py
=> Handle binned faceting with no query matches

INGEST.md
For now this is largely a manual process.  We may wish to automate more of the process in the future.
Fixes #313
=> Add data ingestion documentation

nmdc_server/migrations/versions/ef834f950de9_fix_output_association.py
=> Fix incorrectly named fk reference in an output_association table

nmdc_server/attribute_units.py, web/src/data/api.ts, web/src/encoding.ts, web/src/v2/components/MenuContent.vue
@jbeezley this is ready to go, but the depth unit should be corrected to "centimeters" per https://github.com/microbiomedata/nmdc-server/issues/221
I've made the change here, but I'm not sure if this is the only change I need to make.
fixes #338
=> Use units from database

web/src/v2/views/Search/BiosampleVisGroup.vue
=> Fix tooltips

nmdc_server/models.py, nmdc_server/schemas.py, web/src/data/api.ts, web/src/v2/components/DataObjectTable.vue
Addresses https://github.com/microbiomedata/NMDC_Planning/issues/32
=> Add download count to file list table

nmdc_server/database.py, nmdc_server/migrations/versions/79a0b5695e7d_add_multiomics_study.py, nmdc_server/models.py, nmdc_server/schemas.py
Needed for study counts in #367
=> Add multiomics information to study responses

web/src/v2/views/Search/BiosampleVisGroup.vue
One thing I noticed by doing this is that the definition of a study with a set of omics types is ill-defined.  In the current implementation, a study has an omics type if **any** of it's samples has one.  Furthermore, a study is only included in one upset row--the one containing **all** omics types contained in the study.  This is why, in the screenshot, there are samples with MB + MP but no study... the study containing that sample is included in MB + MG + MP + NOM category instead.
I could include studies in the power set of all omics types it contains, but I'm also not sure if that's what is desired.  I could see an argument that a study should only be included in a category if it contains a biosample that is also in that category.  I'll merge this anyway, and we can revisit how the …
=> Replace static upset data with server-side facets

nmdc_server/api.py, nmdc_server/crud.py, web/Dockerfile, web/nginx.conf.template, web/nginx/modzip/source
This will provide a microservice for streaming downloads.  It also includes a sample api endpoint for generating these downloads, but this will have to be refined to support user defined download carts.
Ref: #354
=> Build mod_zip into base nginx container

web/src/v2/components/BulkDownload.vue, web/src/v2/components/DataObjectTable.vue, web/src/v2/components/DownloadDialog.vue, web/src/v2/views/Search/Layout.vue
=> Update bulk download

nmdc_server/auth.py
Enable brandon to run data ingest.
=> Switch DOI to brandon

web/package.json, web/src/components/Presentation/FilterList.vue, web/src/components/Presentation/Study.vue, web/src/v2/components/DataObjectTable.vue, web/src/v2/components/FilterStringLiteral.vue, web/src/v2/use/usePaginatedResults.ts, web/src/v2/views/IndividualResults/StudyPage.vue, web/src/v2/views/Search/Layout.vue, web/yarn.lock
=> #436 fixes

setup.cfg, web/package.json, web/src/components/Presentation/ConditionChips.vue, web/src/data/api.ts, web/src/v2/components/ClusterMap.vue, web/src/v2/views/Search/BiosampleVisGroup.vue, web/vue.config.js, web/yarn.lock
fixes #366 
https://user-images.githubusercontent.com/4214172/124804844-bac39d80-df28-11eb-9e6c-1a768e7696be.mp4
=> Map pan zoom filter.

web/package.json, web/src/components/Presentation/Histogram2.vue, web/src/v2/views/Search/BiosampleVisGroup.vue
=> Fix histogram colors

web/package.json, web/src/components/Presentation/Histogram2.vue, web/src/v2/views/Search/BiosampleVisGroup.vue
Reverts microbiomedata/nmdc-server#453
=> Revert "Fix histogram colors"

web/src/encoding.ts, web/src/v2/components/FacetedSearch.vue, web/src/v2/views/IndividualResults/StudyPage.vue, web/src/v2/views/Search/BiosampleVisGroup.vue, web/src/v2/views/Search/Sidebar.vue
=> Finish changes for #450

.github/workflows/deploy.yml, docker-compose.yml
Restore deployment after it was disabled for a transition.
=> Restore deploy steps

web/src/components/Presentation/UpSet.vue, web/src/encoding.ts, web/src/v2/views/Search/BiosampleVisGroup.vue, web/src/v2/views/Search/Layout.vue, web/src/v2/views/Search/Sidebar.vue, web/yarn.lock
fixes #410
fixes #449
fixes #400
fixes #391
=> Address some issues:

nmdc_server/auth.py, nmdc_server/cli.py, nmdc_server/config.py, nmdc_server/database.py, nmdc_server/jobs.py, tests/conftest.py, tox.ini
=> Refactor database and test code to remove global state

nmdc_server/ingest/envo.py, nmdc_server/schemas.py, tests/test_envo.py
=> Improve response format of envo tree

nmdc_server/ingest/envo.py
Prior to this change, we were operating under the (incorrect) assumption that
each of the 3 envo facets were present in disjoint trees. This change should
make the code resilient to even significant changes in the ontology.
=> Generate envo trees independently per facet

nmdc_server/ingest/envo.py
This is strictly an improvement in terms of memory performance, time performance, readability, and functional purity.
=> Simplify envo tree building logic

web/src/data/api.ts, web/src/v2/components/FilterTree.vue, web/src/v2/components/MenuContent.vue, web/src/v2/store/index.ts
=> Envo tree counts

web/src/views/Search/BiosampleVisGroup.vue
=> Update BiosampleVisGroup.vue tooltip

web/src/components/BulkDownload.vue, web/src/components/ClusterMap.vue, web/src/components/DataObjectTable.vue, web/src/components/SampleListExpansion.vue, web/src/data/protobuf-descriptor.json, web/src/store/index.ts
=> Persist state through login, allow bulk download without login

web/src/components/MenuContent.vue, web/src/components/Presentation/FilterDate.vue, web/src/components/Presentation/FilterFloat.vue, web/src/views/Search/Sidebar.vue
=> text should say update

docker-compose.dev.yml, nmdc_server/alembic.ini, nmdc_server/api.py, nmdc_server/cli.py, nmdc_server/config.py, nmdc_server/database.py, nmdc_server/ingest/envo.py, nmdc_server/jobs.py, nmdc_server/kegg.py, nmdc_server/utils.py, tests/conftest.py
These can be set via the environment if we need to dynamically tune them.
=> Add database connection pool tuning parameters

nmdc_server/crud.py, web/src/components/FacetedSearch.vue, web/src/components/FilterKegg.vue, web/src/components/MenuContent.vue, web/src/components/Presentation/ConditionChips.vue, web/src/data/api.ts, web/src/encoding.ts
Include exact matches for the kegg term.
=> KEGG text search

README.md, docker-compose.yml, nmdc_server/alembic.ini
This service is unused and was confusing me.
=> Remove ingest db

nmdc_server/ingest/pipeline.py
This is my attempt to find all the "low-hanging fruit" optimizations within the MGA ingest inner loop. 
* Use a projection operator to minimize network data transfer from Mongo
* Use `bulk_save_objects` rather than the dialect `insert`; at least on my local docker-compose environment, this was about 3x faster.
* Instead of doing 1-2 queries per gene function being added (due to `get_or_create`), gather them all up and use an insert with `ON CONFLICT DO NOTHING` behavior. This will massively increase the performance of ingesting the gene functions, but that was admittedly not the hot path here.
=> Optimize MGA ingest

web/src/components/FilterKegg.vue, web/src/components/InvestigatorBio.vue, web/src/components/MenuContent.vue, web/src/encoding.ts, web/src/views/IndividualResults/StudyPage.vue
=> Add brite links

.docker-env, nmdc_server/api.py, nmdc_server/cli.py, nmdc_server/config.py, nmdc_server/ingest/all.py, nmdc_server/ingest/common.py, nmdc_server/jobs.py, nmdc_server/schemas.py
* Fixes ingest where data objects disappear and cause a foreign key issue on the download stats tables.
* Adds "fast ingest" as an option through the swagger page.
fixes #551
=> Fix ingest download stats

.docker-env, README.md, nmdc_server/ingest/all.py, nmdc_server/ingest/data_object.py, setup.py
* SSH tunnel via docker by joining existing network.
* Downgrade broken version of pydantic (1.9.0)
=> SSH tunnel and downgrade pydantic

web/src/components/DataObjectTable.vue
Classic filter/select out of order.  Filter first, then select.
fixes #570
=> Fixes #570

nmdc_server/aggregations.py, nmdc_server/schemas.py, web/.eslintrc.js, web/src/components/ClusterMap.vue, web/src/components/FilterSankeyTree.vue, web/src/components/FilterTree.vue, web/src/components/InvestigatorBio.vue, web/src/components/MenuContent.vue, web/src/data/api.ts, web/src/data/utils.ts, web/src/store/index.ts, web/src/util.js, web/src/views/IndividualResults/IndividualTitle.vue, web/src/views/Search/SearchLayout.vue
fixes #584
fixes #575
fixes #546
Fixes issue with sankey 500
=> Jan updates portal

web/src/views/SubmissionPortal/harmonizerApi.ts
=> Change template source

web/src/components/FilterKegg.vue, web/src/definitions.ts, web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue, web/src/views/SubmissionPortal/Components/StudyForm.vue, web/src/views/SubmissionPortal/store/index.ts
=> Submission definitions

nmdc_server/ingest/kegg.py
=> Module Search Support

nmdc_server/ingest/kegg.py, web/src/App.vue, web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue, web/src/views/SubmissionPortal/Components/SubmissionList.vue, web/src/views/SubmissionPortal/SubmissionView.vue, web/src/views/SubmissionPortal/harmonizerApi.ts
Related to https://docs.google.com/document/d/1WEtHr5ZU40wTDgGNl2ciBE8XPakiuDYWCnu1dOkFfBk/edit#
fixes #634
=> Changes for 4.19

nmdc_server/attribute_units.py, nmdc_server/ingest/biosample.py, nmdc_server/ingest/common.py, nmdc_server/ingest/omics_processing.py
"depth2" is an unexpected object.
=> Fix ingest related to depth and depth2

web/src/views/SubmissionPortal/harmonizerApi.ts
Fix misspelled template names.
=> hrc -> hcr

README.md, nmdc_server/schemas.py
=> Conform CreditAssociation to schema

web/src/App.vue
=> Change links

web/src/views/SubmissionPortal/Components/StudyForm.vue, web/src/views/SubmissionPortal/HarmonizerView.vue, web/src/views/SubmissionPortal/SubmissionView.vue, web/src/views/SubmissionPortal/harmonizerApi.ts
=> Switch DataHarmonizer to prod

web/src/data/utils.ts, web/src/views/SubmissionPortal/HarmonizerView.vue, web/src/views/SubmissionPortal/harmonizerApi.ts
=> Sidebar in DH Submission Portal

web/src/App.vue, web/src/views/SubmissionPortal/HarmonizerView.vue, web/src/views/SubmissionPortal/SubmissionView.vue, web/src/views/SubmissionPortal/harmonizerApi.ts
=> Collapsed errors

README.md
Document procedure for importing database from SQL export.
Get database export file here: https://www.notion.so/National-Microbiome-Data-Collaborative-NMDC-85fbbbc864df4999a7e4f44ba9877c1c
=> DB Import documentation.

nmdc_server/api.py, nmdc_server/auth.py, nmdc_server/crud.py, nmdc_server/migrations/versions/eb9d9e3f3fbc_user_model.py, nmdc_server/schemas.py
While reviewing this PR, I ran into a few issues.  I should have brought these up earlier, so I've made a pass at fixing them myself.
* A user who is already logged in will be unable to create new submissions without logging out and back in, which there is no instruction to do.
* Existing submissions could be missing the author_id foreign key, which will result in a bug allowing non-administrative users to see every submission (or a 500 error, depending on DB state).
* migration that results in users with empty name will never update.
* All authenticated requests (valid tokens) will result in a valid user.  If a request comes in for an authenticated token, a new user will be created if it does not exist.
* User lookup happens during `login_required` dependency function.
* Add migration to …
=> Update user model PR

nmdc_server/api.py, nmdc_server/query.py, nmdc_server/schemas.py, nmdc_server/schemas_submission.py
fixes #711 
Incremental improvement to MetadataSubmission documentation.
=> Add pydantic schemas for metadata submission

web/src/views/SubmissionPortal/SubmissionView.vue
Improve error handling for submission portal loading page.
=> Better error handling for record loading

nmdc_server/schemas_submission.py, web/src/views/SubmissionPortal/Components/SubmissionList.vue, web/src/views/SubmissionPortal/HarmonizerView.vue, web/src/views/SubmissionPortal/store/index.ts
=> Add author column

web/package.json, web/yarn.lock
Update to https://github.com/microbiomedata/nmdc-schema/commit/614426f4c8d772460adaa643c97713ae75e15bdf
=> Upgrade nmdc-schema to v5.0.3

web/src/views/SubmissionPortal/HarmonizerView.vue
Issue #716 
To avoid inadvertent page navigation on horizontal scrolling in data harmonizer, we disable default browser behavior on reaching to the end of scroll.
=> Horizontal scroll

nmdc_server/api.py, nmdc_server/crud.py, nmdc_server/query.py, nmdc_server/schemas.py, web/src/data/api.ts, web/src/plugins/router.ts, web/src/views/User/UserPage.vue
1. Endpoints to list all users and update them (only admin status update supported as now)
2. A new route `/users` that lists all users present in the system
3. This page is only accessible to an admin user
4. Only admin status of a given user can be changed using the toggle switch (in admin column) 
**To-do**
**User Page**
=> User table

docs/data_portal.md
Preview: https://github.com/microbiomedata/nmdc-server/blob/0565aed1ad4b7f9c36fbcda60175b08d1e2c6464/docs/data_portal.md
=> Update ingest docs

web/src/views/SubmissionPortal/HarmonizerView.vue, web/src/views/SubmissionPortal/harmonizerApi.ts
Closes #757 
This auto updates submission data when any cell is changed.
=> Auto update submission data on change

nmdc_server/ingest/biosample.py, nmdc_server/ingest/common.py, nmdc_server/ingest/study.py
=> Ingest fixes

web/src/components/InvestigatorBio.vue, web/src/views/Search/SearchLayout.vue
Fix miscellaneous frontend quirks for a study page.
=> Frontend fixes

web/package.json, web/src/components/Presentation/DateInput.vue, web/yarn.lock
Allows the user to enter text for the date field.
=> Type in date

web/src/components/Presentation/DateInput.vue
Changes date format in search from e.g. "Aug 1st, 2014" to "Aug 1, 2014".
=> Drop date suffix

web/package.json, web/public/index.html, web/yarn.lock
Updates validation. Fixes validation failing.
=> DataHarmonizer upgrade

web/src/views/SubmissionPortal/HarmonizerView.vue
Closes #759. Help text is shown by default.
=> Make sidebar toggle-able

web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue, web/yarn.lock
With https://github.com/microbiomedata/sheets_and_friends/commit/8961887aa48f254dcc8c678113ed28df84686d25, the user can select any combination of JGI-Metagenome/Metatranscriptome.
=> Allow the selection of `soil_emsl_jgi_mt`

web/src/views/SubmissionPortal/HarmonizerView.vue
Small bug fix for missing null check in multitab DH work.
=> Fix bug caused by empty sheet data

web/src/views/SubmissionPortal/HarmonizerView.vue
Fixes https://github.com/microbiomedata/issues/issues/76
The diff makes it look like more changes than it really is. The core is moving data synchronizing logic that used to exist only in `changeTemplate` to a new function called `synchronizeTabData`. That function can then be called on tab change _and_ on export (`downloadSamples`). I had to shuffle around the order of some functions to keep the linter happy.
=> Run DataHarmonizer tab data sync before performing export

web/package.json, web/src/views/SubmissionPortal/harmonizerApi.ts, web/yarn.lock
Fixes https://github.com/microbiomedata/issues/issues/88
To see the difference, in the DataHarmonizer view of the submission portal double-click on the header of any column that has a drop-down menu. In the resulting modal, there should not be a "Menus" entry.
=> Remove "Menus" entry from column help

LICENSE
Adding the standard 3 clause LBL BSD license. 
See: https://spdx.org/licenses/BSD-3-Clause-LBNL.html
=> BSD License

web/src/definitions.ts, web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue
Fixes https://github.com/microbiomedata/issues/issues/128
Fixes https://github.com/microbiomedata/issues/issues/129
=> Grammar updates in submission portal forms

web/package.json, web/yarn.lock
=> Upgrade to submission schema v1.0.1

nmdc_server/schemas.py
This prevents validation errors when ingesting from mongo.
=> Allow lists for values in annotation column

web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue, web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue, web/src/views/SubmissionPortal/Components/SubmissionStepper.vue, web/src/views/SubmissionPortal/store/index.ts
Fixes https://github.com/microbiomedata/nmdc-server/issues/923
Fixes https://github.com/microbiomedata/nmdc-server/issues/922
=> Typo fixes

web/package.json, web/yarn.lock
Part 2 of fixing https://github.com/microbiomedata/issues/issues/196
=> Upgrade to submission schema v1.0.2

web/src/menus.ts
Fixes https://github.com/microbiomedata/issues/issues/269
=> Sync header with WordPress header

web/package.json, web/yarn.lock
Another new version! This one updates a few validation patterns but that's about it as far as user-facing changes.
=> Upgrade to submission schema 7.6.5

setup.py
=> Pin dnspython==2.3.0

web/src/components/Presentation/AuthButton.vue
This was preventing a successful deployment of the client image. 
Fix #1039
=> Fix format of `AuthButton.vue`

docs/development.md
This branch contains a fix for issue #1041.
Hi @marySalvi, I assigned it to you because GitHub shows you as the only previous editor of the file I edited.
=> Fix invalid ORCID Redirect URI in docs (#1041)

web/src/data/api.ts, web/src/views/IndividualResults/StudyPage.vue
closes #1010 and closes #1030  
Updates study page UI to display multi value DOIs for award, publication and dataset.
=> Award dois UI

web/src/use/usePaginatedResults.ts
Reverts microbiomedata/nmdc-server#1056
This change did not play nicely with the submissions list and users list views.
=> Revert "Fix results race condition"

web/package.json, web/yarn.lock
Related to https://github.com/microbiomedata/submission-schema/issues/140
=> Upgrade to submission-schema 8.1.1

web/src/components/Presentation/DateHistogram.vue, web/src/components/Presentation/TimeHistogram.vue
=> Show total dataset and selected dataset on chart

nmdc_server/ingest/doi.py, nmdc_server/ingest/study.py, nmdc_server/models.py, nmdc_server/schemas.py, web/src/data/api.ts, web/src/views/IndividualResults/StudyPage.vue
=> Change ingest code to include new DOI Class

web/src/views/SubmissionPortal/HarmonizerView.vue
Fixes #1047 (also related to https://github.com/microbiomedata/issues/issues/543)
=> Fix XLSX import when columns are reordered or missing

.github/workflows/deploy.yml
😭 😭 
I forgot you can't use `env` in `if` at _that_ level.
=> Remove illegal use of env in deploy.yaml

.github/workflows/deploy.yml
😭 😭 😭 
Variables in the `env` context are actually always strings.
=> Fix boolean comparison in workflow file

nmdc_server/query.py
Fix #1072 
The NMDC Data Portal allows adding filters on multiple properties across different levels of the NMDC schema hierarchy. For example, one can add a search filter at the biosample level (depth) and see results from the study and data object level.
Prior to this change, searching across multiple hierarchies could introduce some unexpected results due to how our queries were being constructed. Examples of this inconsistency are documented fairly well in #1072 and #1085.
The fix for #1085 was the first step toward fixing this larger problem, which this PR aims to expand to be a fully fledged fix.
=> Fix multi-tiered search

web/src/components/InvestigatorBio.vue, web/src/data/api.ts, web/src/views/IndividualResults/StudyPage.vue, web/src/views/Search/SearchLayout.vue
- Limits Team section to three lines and overflow scrolls
- Does not show PI and ORCID on consortia
- Study_count on Parent studies is a sum of its count  and its childrens' counts
- Fixes bug where consortia children were not disabled when the parent was selected.
=> Study page fixes

nmdc_server/api.py
At this point not getting children results would be unexpected behavior
=> Remove flat option for study api

web/src/components/Presentation/SearchResults.vue, web/src/views/Search/SearchLayout.vue
Remove counts for studies and consortia. Make both expandable defaulting to ~~closed~~ open.
=> Update display of study results

pyproject.toml
Related to https://github.com/microbiomedata/nmdc-schema/issues/1840
This should fix the dev ingest which is failing at the moment.
=> Upgrade to nmdc-schema 10.1.4

web/src/use/usePaginatedResults.ts
=> Reset offset to 0 when items per page is updated

nmdc_server/ingest/study.py
Stores PI url in study annotations and logs potential errors when requesting the image during ingest.
=> Store PI image url on ingest and log request errors

web/src/views/SubmissionPortal/SubmissionView.vue
Fixes #1235 
This is ready for review, but I'm leaving it as a draft until I've made a new release tag on this branch.
=> Only show AppBanner component on submission portal Home page

web/package.json, web/yarn.lock
A small batch of dependabot-suggested npm package updates
=> Bump vuetify and moment

web/src/use/usePaginatedResults.ts
=> Remove limit reset for pagination when conditions change.

web/src/menus.ts
Re: https://github.com/microbiomedata/issues/issues/699 (will close the issue after the WordPress site is updated as well)
=> Add FAQs, Blog, and Media Materials links to header menu

web/src/views/IndividualResults/SamplePage.vue, web/src/views/IndividualResults/StudyPage.vue, web/src/views/Search/SearchLayout.vue, web/src/views/SubmissionPortal/SubmissionView.vue, web/src/views/User/UserPage.vue
In this branch, I added `v-if="false"` to all the `<AppBanner />` elements. My goal was to hide them all from the UI, without making lots of code changes and without violating any minting rules.
=> Refrain from rendering any `<AppBanner />` elements

web/src/views/Search/SearchSidebar.vue
=> Standardize sample verbage

nmdc_server/api.py
Small PR to add the environment the GH issue was created from.
=> Add source to gh issue creation

web/src/views/IndividualResults/StudyPage.vue
=> Change router to go to homepage instead of previous history index

web/src/views/SubmissionPortal/SubmissionView.vue
Removes unnecessary container which created unwanted padding.
=> Remove unnecesary container

web/src/menus.ts
Fixes https://github.com/microbiomedata/issues/issues/778
=> Add Data Integration link to header menus

web/src/util.js
I think the PR title is self-explanatory.
=> Replace double quotes with single quotes (to appease linter)

web/package.json, web/src/components/FacetedSearch.vue, web/src/components/MenuContent.vue, web/src/data/api.ts, web/src/views/Search/SearchSidebar.vue, web/src/views/SubmissionPortal/Components/StudyForm.vue, web/src/views/SubmissionPortal/Components/SubmissionContextForm.vue, web/src/views/SubmissionPortal/Components/SubmissionContextShippingForm.vue, web/yarn.lock
closes #1303 
- Adds tooltip for GOLD Ecosystems
- Also converts all schema JSON references to yaml
=> 1303 add gold tooltip

nmdc_server/api.py
=> Add study id to partial search

web/src/components/AppBanner.vue, web/src/views/IndividualResults/SamplePage.vue, web/src/views/IndividualResults/StudyPage.vue, web/src/views/Search/SearchLayout.vue, web/src/views/SubmissionPortal/SubmissionView.vue, web/src/views/User/UserDetailPage.vue, web/src/views/User/UserPage.vue
In this branch, I updated the `AppBanner` Vue component so it describes the upcoming maintenance events. I also updated the (multiple) boolean flags so that the banner appears on the web page.
Here's what the resulting banner looks like:
Finally, I added some `TODO` comments about consolidating those boolean flags into a single variable references within those `v-if` conditions.
=> Add banner announcing upcoming maintenance events (October 15-16)

web/src/components/AppBanner.vue, web/src/store/index.ts, web/src/views/IndividualResults/SamplePage.vue, web/src/views/IndividualResults/StudyPage.vue, web/src/views/Search/SearchLayout.vue, web/src/views/SubmissionPortal/SubmissionView.vue, web/src/views/User/UserDetailPage.vue, web/src/views/User/UserPage.vue
Also consolidates all of the boolean checks into one place (`AppBanner.vue`).
=> Remove Berkeley update banner from data and submission portals

docs/development.md
⚠️ These are "quick 'n dirty" notes written by someone that may have a fever (he can't find his thermometer).
=> Incorporate feedback from run-through with new developer

web/src/encoding.ts
=> Change base url and order of string parsing

web/src/encoding.ts
=> Change base urls for kegg

nmdc_server/query.py
Fix #1462 
This fixes some bugs that occur when there is no mapping from a GO term to either KEGG or PFAM. It does NOT prevent the user from selecting such terms.
A search for this particular GO term incorrectly reports that it matches ALL samples. The search function technically fails to handle this case, since it expects that the GO term has at least one mapped term.
The same query now (correctly) returns no biosample results. The code that translates the GO term to KEGG and PFAM terms handles the case where no such mappings exist. Additionally, some of the logic that transforms search terms into those stored in the database has been streamlined.
=> Fix GO search bugs

web/src/views/IndividualResults/StudyPage.vue
=> Fix logic for Additional Resources section

web/src/encoding.ts
=> Fix typo in kegg URL

.git-blame-ignore-revs, nmdc_server/migrations/versions/4b2d6ee63752_add_is_test_submission_to_SubmissionMetadata.py, nmdc_server/migrations/versions/780ab86a4f27_squashed_initial.py
=> Format migration files

nmdc_server/api.py, tests/test_submission.py
Updating the `get_metadata_submissions_report` endpoint to include `is_test_submission` and `date_last_modified`
=> Update API endpoint to support date_last_modified

web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
In Submission Portal, ensure that user enters an appropriate project ID using a regex check for: 
- 6 digit number for JGI
- 5 digit number for EMSL
=> Validate JGI and EMSL project IDs

web/src/views/SubmissionPortal/Components/SubmissionContextShippingForm.vue
Closes #1281 
Adds back requirements requested here:
https://github.com/microbiomedata/nmdc-server/issues/1281#issuecomment-2625946392
=> Make sample info and user info required

web/src/views/SubmissionPortal/Components/MultiOmicsDataForm.vue
Relevant issue: https://github.com/microbiomedata/submission-schema/issues/315
This is a small PR meant solely to update the helper text for JGI and EMSL proposal IDs
=> Update study page helper text for proposal IDs

web/src/views/SubmissionPortal/Components/TemplateChooser.vue
Relevant issue: https://github.com/microbiomedata/issues/issues/998
This PR is pretty small, it just updates some classes on the template chooser to adjust spacing between checkboxes.
=> Update spacing on template chooser checkboxes

nmdc_server/api.py, tests/test_submission.py
May resolve https://github.com/microbiomedata/issues/issues/1155 
This PR adds the `Date Created` column to the metadata submission report and updates the related test.
=> Add date created to metadata submission report

web/src/plugins/router.ts, web/src/views/SubmissionPortal/Components/SubmissionStepper.vue, web/src/views/SubmissionPortal/Components/TemplateChooser.vue, web/src/views/SubmissionPortal/store/index.ts
This PR changes the metadata submission to not have a default template choice for the data harmonizer.
Now users must select at least one template.
Supporting changes were also added for clarity on the template selection page.
Relevant issue: https://github.com/microbiomedata/issues/issues/1002
=> Remove default template choice

pyproject.toml
Upgrading to nmdc-submission-schema 11.7.1 in order to bring in the changes for https://github.com/microbiomedata/submission-schema/issues/322
=> Upgrade to nmdc-submission-schema 11.7.1

nmdc_server/api.py
=> Minimal logging for zipstreamer downloads

nmdc_server/api.py
I'm not exactly sure what kinds of messages would be useful to have for zipstreamer monitoring. I think logging each chunk is overkill. This change will log a message if it takes zipstreamer more than 5 seconds to send a chunk.
This is related to #1648 in that the number chosen for this change is the [default timeout for HTTPX](https://www.python-httpx.org/advanced/timeouts/). Whether or not this kind of logging proves useful is yet to be seen, so we should revisit these changes after resolving the zipstreamer issues and find more intentional fixes to the issues that we've been seeing.
=> Log a message when zipstreamer seems starved

web/src/encoding.ts
Closes https://github.com/microbiomedata/nmdc-server/issues/270
=> Add descriptions from schema to additional search facet

nmdc_server/migrations/versions/9a0ff33a4e6b_update_created_on_auth_code.py, nmdc_server/models.py
Fixes minor typing bug when comparing times.
=> Change created field on auth code to be timezone aware

nmdc_server/ingest/omics_processing.py, web/src/components/AmpliconObjectDataTable.vue
Pull in target fields from `material_processing_set` record
=> Amplicon fix

web/src/menus.ts
On this branch, I made the two changes listed in #1768; i.e. I renamed a top-level menu item and introduced a new second-level menu item.
=> Update navigation menu to match WordPress website

docs/development.md, nmdc_server/cli.py
This captures some of the discussion from a recent knowledge sharing session. It adds some new imports to the `nmdc-server shell` CLI command that can be used to play around with how the search functionality works, and adds documentation to `development.md` on how to use the `shell` command in ways that I've found useful.
@eecavanna @codytodonnell @shreddd ideally this new documentation is helpful for onboarding new engineers and providing some tools to better understand the system. Feel free to chime in on how this can be more clear, and if possible please double-check my work (i.e, walk through the examples). If there are any lingering questions about the new material in the developer docs don't hesitate to ask. I will plan on merging this early next week.
I'm only requesting review …
=> Document helpful use cases for `nmdc-server shell`
